2019-07-22 11:54:36,356 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init-local' at Mon, 22 Jul 2019 11:54:36 +0000. Up 6.89 seconds.
2019-07-22 11:54:36,356 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:36,356 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:36,359 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:36,360 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:36,360 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2019-07-22 11:54:36,360 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
2019-07-22 11:54:36,360 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2019-07-22 11:54:36,360 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:36,360 - stages.py[DEBUG]: no cache found
2019-07-22 11:54:36,360 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2019-07-22 11:54:36,360 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:36,363 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:36,363 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2019-07-22 11:54:36,391 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:36,391 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:36,416 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceOpenStackLocal', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceEc2Local']
2019-07-22 11:54:36,417 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2019-07-22 11:54:36,417 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2019-07-22 11:54:36,417 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,417 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,418 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,420 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,421 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,421 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,421 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,421 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,421 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:36,421 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:36,421 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:36,421 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec2e672f-5dc1-c2ba-f346-7a6d73145fa6
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2019-07-22 11:54:36,422 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,423 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,425 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,438 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,450 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,462 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: no local data found from DataSourceNoCloud
2019-07-22 11:54:36,462 - handlers.py[DEBUG]: start: init-local/search-ConfigDrive: searching for local data from DataSourceConfigDrive
2019-07-22 11:54:36,462 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceConfigDrive.DataSourceConfigDrive'>
2019-07-22 11:54:36,462 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,463 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,464 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,466 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,467 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,469 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,481 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,493 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=config-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,505 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONFIG-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,517 - DataSourceConfigDrive.py[DEBUG]: devices=[] dslist=['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None']
2019-07-22 11:54:36,517 - handlers.py[DEBUG]: finish: init-local/search-ConfigDrive: SUCCESS: no local data found from DataSourceConfigDrive
2019-07-22 11:54:36,518 - handlers.py[DEBUG]: start: init-local/search-OpenNebula: searching for local data from DataSourceOpenNebula
2019-07-22 11:54:36,518 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenNebula.DataSourceOpenNebula'>
2019-07-22 11:54:36,518 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,518 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONTEXT', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,530 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CDROM', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,542 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,554 - handlers.py[DEBUG]: finish: init-local/search-OpenNebula: SUCCESS: no local data found from DataSourceOpenNebula
2019-07-22 11:54:36,554 - handlers.py[DEBUG]: start: init-local/search-DigitalOcean: searching for local data from DataSourceDigitalOcean
2019-07-22 11:54:36,554 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceDigitalOcean.DataSourceDigitalOcean'>
2019-07-22 11:54:36,554 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,554 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,556 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,558 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,559 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,560 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,560 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,560 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,560 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:36,560 - util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
2019-07-22 11:54:36,560 - util.py[DEBUG]: Read 4 bytes from /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:36,560 - util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Xen
2019-07-22 11:54:36,560 - handlers.py[DEBUG]: finish: init-local/search-DigitalOcean: SUCCESS: no local data found from DataSourceDigitalOcean
2019-07-22 11:54:36,560 - handlers.py[DEBUG]: start: init-local/search-Azure: searching for local data from DataSourceAzure
2019-07-22 11:54:36,560 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'>
2019-07-22 11:54:36,561 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,561 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,562 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,564 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,566 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,566 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,566 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,566 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,566 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:36,566 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:36,566 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:36,566 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:36,566 - DataSourceAzure.py[DEBUG]: Non-Azure DMI asset tag '' discovered.
2019-07-22 11:54:36,566 - handlers.py[DEBUG]: finish: init-local/search-Azure: SUCCESS: no local data found from DataSourceAzure
2019-07-22 11:54:36,567 - handlers.py[DEBUG]: start: init-local/search-OVF: searching for local data from DataSourceOVF
2019-07-22 11:54:36,567 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'>
2019-07-22 11:54:36,567 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,567 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,568 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,570 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,572 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,572 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,572 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,572 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,572 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:36,572 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:36,572 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:36,572 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:36,572 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2019-07-22 11:54:36,573 - util.py[DEBUG]: Read 1991 bytes from /proc/mounts
2019-07-22 11:54:36,573 - util.py[DEBUG]: Fetched {'systemd-1': {'opts': 'rw,relatime,fd=23,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'fstype': 'autofs'}, 'mqueue': {'opts': 'rw,relatime', 'mountpoint': '/dev/mqueue', 'fstype': 'mqueue'}, 'cgroup': {'opts': 'rw,nosuid,nodev,noexec,relatime,memory', 'mountpoint': '/sys/fs/cgroup/memory', 'fstype': 'cgroup'}, 'proc': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/proc', 'fstype': 'proc'}, '/dev/xvda1': {'opts': 'rw,relatime,discard,data=ordered', 'mountpoint': '/', 'fstype': 'ext4'}, 'hugetlbfs': {'opts': 'rw,relatime', 'mountpoint': '/dev/hugepages', 'fstype': 'hugetlbfs'}, 'debugfs': {'opts': 'rw,relatime', 'mountpoint': '/sys/kernel/debug', 'fstype': 'debugfs'}, 'pstore': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/fs/pstore', 'fstype': 'pstore'}, 'devpts': {'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'mountpoint': '/dev/pts', 'fstype': 'devpts'}, 'tmpfs': {'opts': 'ro,nosuid,nodev,noexec,mode=755', 'mountpoint': '/sys/fs/cgroup', 'fstype': 'tmpfs'}, 'securityfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/kernel/security', 'fstype': 'securityfs'}, 'fusectl': {'opts': 'rw,relatime', 'mountpoint': '/sys/fs/fuse/connections', 'fstype': 'fusectl'}, 'udev': {'opts': 'rw,nosuid,relatime,size=30907648k,nr_inodes=7726912,mode=755', 'mountpoint': '/dev', 'fstype': 'devtmpfs'}, 'sysfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys', 'fstype': 'sysfs'}} mounts from proc
2019-07-22 11:54:36,573 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:36,585 - handlers.py[DEBUG]: finish: init-local/search-OVF: SUCCESS: no local data found from DataSourceOVF
2019-07-22 11:54:36,585 - handlers.py[DEBUG]: start: init-local/search-OpenStackLocal: searching for local data from DataSourceOpenStackLocal
2019-07-22 11:54:36,585 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenStack.DataSourceOpenStackLocal'>
2019-07-22 11:54:36,585 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,586 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,587 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,588 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,590 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,590 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,590 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,590 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,590 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:36,590 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:36,590 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:36,590 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:36,591 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,592 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,594 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,595 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,595 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,595 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,596 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,596 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:36,596 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:36,596 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:36,596 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:36,596 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,596 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,596 - handlers.py[DEBUG]: finish: init-local/search-OpenStackLocal: SUCCESS: no local data found from DataSourceOpenStackLocal
2019-07-22 11:54:36,596 - handlers.py[DEBUG]: start: init-local/search-CloudSigma: searching for local data from DataSourceCloudSigma
2019-07-22 11:54:36,596 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceCloudSigma.DataSourceCloudSigma'>
2019-07-22 11:54:36,596 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,596 - DataSourceCloudSigma.py[DEBUG]: determining hypervisor product name via dmi data
2019-07-22 11:54:36,596 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,598 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,600 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,601 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,601 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,602 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,602 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,602 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:36,602 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:36,602 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:36,602 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:36,602 - DataSourceCloudSigma.py[DEBUG]: detected hypervisor as HVM domU
2019-07-22 11:54:36,602 - handlers.py[DEBUG]: finish: init-local/search-CloudSigma: SUCCESS: no local data found from DataSourceCloudSigma
2019-07-22 11:54:36,602 - handlers.py[DEBUG]: start: init-local/search-SmartOS: searching for local data from DataSourceSmartOS
2019-07-22 11:54:36,602 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceSmartOS.DataSourceSmartOS'>
2019-07-22 11:54:36,603 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,604 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,606 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,607 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,608 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,608 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,608 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,608 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:36,608 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:36,608 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:36,608 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:36,608 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,608 - DataSourceSmartOS.py[DEBUG]: Not running on smartos
2019-07-22 11:54:36,608 - handlers.py[DEBUG]: finish: init-local/search-SmartOS: SUCCESS: no local data found from DataSourceSmartOS
2019-07-22 11:54:36,608 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2019-07-22 11:54:36,609 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2019-07-22 11:54:36,609 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:36,609 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2019-07-22 11:54:36,609 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2019-07-22 11:54:36,609 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,611 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,612 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,614 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:36,614 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:36,614 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:36,614 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:36,615 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:36,615 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:36,615 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:36,615 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec2e672f-5dc1-c2ba-f346-7a6d73145fa6
2019-07-22 11:54:36,615 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_platform=AWS
2019-07-22 11:54:36,615 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:36,615 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:36,615 - util.py[DEBUG]: Reading from /sys/class/net/ens3/name_assign_type (quiet=False)
2019-07-22 11:54:36,616 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/name_assign_type
2019-07-22 11:54:36,616 - util.py[DEBUG]: Reading from /sys/class/net/ens3/carrier (quiet=False)
2019-07-22 11:54:36,616 - util.py[DEBUG]: Reading from /sys/class/net/ens3/dormant (quiet=False)
2019-07-22 11:54:36,616 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:36,616 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:36,616 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:36,616 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:36,616 - dhcp.py[DEBUG]: Performing a dhcp discovery on ens3
2019-07-22 11:54:36,616 - util.py[DEBUG]: Copying /sbin/dhclient to /var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient
2019-07-22 11:54:36,633 - util.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,651 - util.py[DEBUG]: Running command ['/var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient.pid', 'ens3', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,729 - util.py[DEBUG]: All files appeared after 0 seconds: ['/var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient.pid', '/var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhcp.leases']
2019-07-22 11:54:36,729 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient.pid (quiet=False)
2019-07-22 11:54:36,729 - util.py[DEBUG]: Read 5 bytes from /var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhclient.pid
2019-07-22 11:54:36,729 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhcp.leases (quiet=False)
2019-07-22 11:54:36,729 - util.py[DEBUG]: Read 513 bytes from /var/tmp/cloud-init/cloud-init-dhcp-et9n_j42/dhcp.leases
2019-07-22 11:54:36,730 - dhcp.py[DEBUG]: Received dhcp lease on ens3 for 10.0.0.235/255.255.255.0
2019-07-22 11:54:36,730 - __init__.py[DEBUG]: Attempting setup of ephemeral network on ens3 with 10.0.0.235/24 brd 10.0.0.255
2019-07-22 11:54:36,730 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '10.0.0.235/24', 'broadcast', '10.0.0.255', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,731 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,735 - util.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,736 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', 'default', 'via', '10.0.0.1', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,741 - util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.003 seconds
2019-07-22 11:54:36,741 - util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.000 seconds
2019-07-22 11:54:36,741 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2019-07-22 11:54:36,742 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2009-04-04/meta-data/instance-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2009-04-04/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 50.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,746 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2009-04-04/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:36,746 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2019-07-22 11:54:36,746 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:36,748 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:36,748 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
2019-07-22 11:54:36,748 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/user-data', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,750 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,751 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 268b) after 1 attempts
2019-07-22 11:54:36,752 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,753 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 30b) after 1 attempts
2019-07-22 11:54:36,753 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,755 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
2019-07-22 11:54:36,755 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,756 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1 (200, 3b) after 1 attempts
2019-07-22 11:54:36,756 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,758 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2019-07-22 11:54:36,758 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,760 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0 (200, 3b) after 1 attempts
2019-07-22 11:54:36,760 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,762 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/ (200, 26b) after 1 attempts
2019-07-22 11:54:36,762 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/info' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/info', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,763 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/info (200, 245b) after 1 attempts
2019-07-22 11:54:36,763 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,765 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
2019-07-22 11:54:36,765 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,767 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2019-07-22 11:54:36,767 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,768 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
2019-07-22 11:54:36,769 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,770 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2019-07-22 11:54:36,770 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,772 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2019-07-22 11:54:36,772 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,773 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ (200, 230b) after 1 attempts
2019-07-22 11:54:36,774 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,775 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/ (200, 10b) after 1 attempts
2019-07-22 11:54:36,775 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/54.77.7.87' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/54.77.7.87', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,777 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/ipv4-associations/54.77.7.87 (200, 10b) after 1 attempts
2019-07-22 11:54:36,777 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/interface-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/interface-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,778 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/interface-id (200, 21b) after 1 attempts
2019-07-22 11:54:36,778 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,780 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-id (200, 24b) after 1 attempts
2019-07-22 11:54:36,780 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/owner-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/owner-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,781 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/owner-id (200, 12b) after 1 attempts
2019-07-22 11:54:36,782 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-ipv4s' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,783 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-ipv4s (200, 10b) after 1 attempts
2019-07-22 11:54:36,783 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-groups' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-groups', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,784 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:36,785 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-block' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,786 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:36,786 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-ipv4-cidr-block' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,788 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:36,788 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-ipv4s' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,790 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-ipv4s (200, 10b) after 1 attempts
2019-07-22 11:54:36,790 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/mac' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/mac', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,792 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/mac (200, 17b) after 1 attempts
2019-07-22 11:54:36,792 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-hostname' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,793 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/public-hostname (200, 46b) after 1 attempts
2019-07-22 11:54:36,794 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-hostname' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,795 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:36,795 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,797 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-id (200, 21b) after 1 attempts
2019-07-22 11:54:36,797 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/device-number' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/device-number', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,798 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/device-number (200, 1b) after 1 attempts
2019-07-22 11:54:36,798 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-blocks' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,800 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
2019-07-22 11:54:36,800 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-group-ids' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,801 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:49:3d:dc:77:d6/security-group-ids (200, 20b) after 1 attempts
2019-07-22 11:54:36,801 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,803 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
2019-07-22 11:54:36,803 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,804 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2019-07-22 11:54:36,805 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,806 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 68b) after 1 attempts
2019-07-22 11:54:36,806 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,808 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 448b) after 1 attempts
2019-07-22 11:54:36,808 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,809 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
2019-07-22 11:54:36,809 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,811 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
2019-07-22 11:54:36,811 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,812 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
2019-07-22 11:54:36,813 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,814 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
2019-07-22 11:54:36,814 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,815 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
2019-07-22 11:54:36,816 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,817 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 10b) after 1 attempts
2019-07-22 11:54:36,817 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,819 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2019-07-22 11:54:36,819 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,820 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
2019-07-22 11:54:36,820 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,822 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:36,822 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,823 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
2019-07-22 11:54:36,824 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,825 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
2019-07-22 11:54:36,825 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,827 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 10b) after 1 attempts
2019-07-22 11:54:36,827 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,828 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:36,828 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,830 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 46b) after 1 attempts
2019-07-22 11:54:36,830 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,831 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 40b) after 1 attempts
2019-07-22 11:54:36,831 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,833 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 10b) after 1 attempts
2019-07-22 11:54:36,833 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,834 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:36,835 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,836 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
2019-07-22 11:54:36,836 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,839 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
2019-07-22 11:54:36,839 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,840 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
2019-07-22 11:54:36,840 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,842 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1114b) after 1 attempts
2019-07-22 11:54:36,842 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,843 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
2019-07-22 11:54:36,844 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'allow_redirects': True, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'timeout': 5.0, 'method': 'GET'} configuration
2019-07-22 11:54:36,845 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2019-07-22 11:54:36,845 - util.py[DEBUG]: Crawl of metadata service took 0.107 seconds
2019-07-22 11:54:36,845 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', 'default', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,847 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'down'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,882 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '10.0.0.235/24', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,885 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2019-07-22 11:54:36,886 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2019-07-22 11:54:36,886 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:36,886 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:36,886 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,896 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:36,896 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:36,896 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,898 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:36,898 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:36,898 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,901 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:36,901 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:36,901 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,902 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,902 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:36,902 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:36,902 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0552f5d9cc06a76fd'
2019-07-22 11:54:36,903 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0552f5d9cc06a76fd/datasource (quiet=False)
2019-07-22 11:54:36,903 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/datasource - wb: [644] 39 bytes
2019-07-22 11:54:36,904 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:36,904 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:36,904 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2019-07-22 11:54:36,904 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:36,905 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:36,905 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2019-07-22 11:54:36,906 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9170 bytes
2019-07-22 11:54:36,906 - main.py[DEBUG]: [local] init will now be targeting instance id: i-0552f5d9cc06a76fd. new=True
2019-07-22 11:54:36,906 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:36,906 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:36,906 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,916 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:36,916 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:36,916 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,917 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:36,917 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:36,918 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,921 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:36,921 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:36,921 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,921 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:36,921 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:36,922 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:36,923 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-0-235.eu-west-1.compute.internal (ip-10-0-0-235)
2019-07-22 11:54:36,923 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:36,923 - util.py[DEBUG]: Read 7 bytes from /etc/hostname
2019-07-22 11:54:36,923 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 14 bytes
2019-07-22 11:54:36,923 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-10-0-0-235
2019-07-22 11:54:36,923 - util.py[DEBUG]: Running command ['hostname', 'ip-10-0-0-235'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,926 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:36,926 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:36,927 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'mac_address': '02:49:3d:dc:77:d6', 'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'name': 'ens3'}]}
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:36,927 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:36,928 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:36,928 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:36,928 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:36,928 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:36,928 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:36,928 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:36,928 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:36,928 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:36,928 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:36,928 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:36,928 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,931 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:36,933 - __init__.py[DEBUG]: no work necessary for renaming of [['02:49:3d:dc:77:d6', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:36,933 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 1, 'config': [{'mac_address': '02:49:3d:dc:77:d6', 'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'name': 'ens3'}]}
2019-07-22 11:54:36,933 - __init__.py[DEBUG]: Selected renderer 'eni' from priority list: None
2019-07-22 11:54:36,936 - util.py[DEBUG]: Writing to /etc/network/interfaces.d/50-cloud-init.cfg - wb: [644] 367 bytes
2019-07-22 11:54:36,936 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 96 bytes
2019-07-22 11:54:36,936 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2019-07-22 11:54:36,937 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:36,938 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:36,938 - util.py[DEBUG]: cloud-init mode 'init' took 0.614 seconds (0.61)
2019-07-22 11:54:36,938 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2019-07-22 11:54:37,468 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init' at Mon, 22 Jul 2019 11:54:37 +0000. Up 8.00 seconds.
2019-07-22 11:54:37,468 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:37,468 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:37,470 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:37,470 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:37,470 - util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,473 - util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,475 - util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2019-07-22 11:54:37,477 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
2019-07-22 11:54:37,478 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
2019-07-22 11:54:37,478 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2019-07-22 11:54:37,478 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:37,478 - util.py[DEBUG]: Read 9170 bytes from /var/lib/cloud/instance/obj.pkl
2019-07-22 11:54:37,480 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2019-07-22 11:54:37,480 - util.py[DEBUG]: Read 20 bytes from /run/cloud-init/.instance-id
2019-07-22 11:54:37,480 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:37,480 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:37,480 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:37,481 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:37,481 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,492 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:37,492 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:37,492 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,493 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:37,493 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:37,493 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,496 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:37,496 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:37,496 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,497 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,497 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:37,497 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:37,498 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0552f5d9cc06a76fd'
2019-07-22 11:54:37,498 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0552f5d9cc06a76fd/datasource (quiet=False)
2019-07-22 11:54:37,498 - util.py[DEBUG]: Read 39 bytes from /var/lib/cloud/instances/i-0552f5d9cc06a76fd/datasource
2019-07-22 11:54:37,498 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/datasource - wb: [644] 39 bytes
2019-07-22 11:54:37,499 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:37,499 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:37,499 - util.py[DEBUG]: Read 20 bytes from /var/lib/cloud/data/instance-id
2019-07-22 11:54:37,499 - stages.py[DEBUG]: previous iid found to be i-0552f5d9cc06a76fd
2019-07-22 11:54:37,499 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:37,500 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:37,500 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2019-07-22 11:54:37,500 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9186 bytes
2019-07-22 11:54:37,501 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0552f5d9cc06a76fd. new=False
2019-07-22 11:54:37,501 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:37,501 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:37,501 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,511 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:37,511 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:37,511 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,513 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:37,513 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:37,513 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,516 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:37,516 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:37,516 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,517 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,517 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:37,517 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:37,518 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:37,518 - stages.py[DEBUG]: applying net config names for {'config': [{'type': 'physical', 'mac_address': '02:49:3d:dc:77:d6', 'subnets': [{'type': 'dhcp4'}], 'name': 'ens3'}], 'version': 1}
2019-07-22 11:54:37,518 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:37,519 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:37,519 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:37,520 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:37,520 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:37,520 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:37,520 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:37,520 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:37,520 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:37,520 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:37,520 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,522 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,523 - __init__.py[DEBUG]: no work necessary for renaming of [['02:49:3d:dc:77:d6', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:37,524 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
2019-07-22 11:54:37,524 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2019-07-22 11:54:37,524 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2019-07-22 11:54:37,524 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/user-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:37,527 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/user-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:37,527 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/vendor-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:37,528 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/vendor-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:37,529 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:37,529 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:37,530 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:37,530 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/consume_data - wb: [644] 25 bytes
2019-07-22 11:54:37,530 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/consume_data'>)
2019-07-22 11:54:37,530 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2019-07-22 11:54:37,531 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2019-07-22 11:54:37,531 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']]
2019-07-22 11:54:37,531 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2019-07-22 11:54:37,531 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2019-07-22 11:54:37,531 - stages.py[DEBUG]: Added default handler for {'text/upstart-job'} from UpstartJobPartHandler: [['text/upstart-job']]
2019-07-22 11:54:37,531 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,531 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']] (__begin__, None, 3) with frequency once-per-instance
2019-07-22 11:54:37,531 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,531 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: {'Content-Disposition': 'attachment; filename="part-001"', 'Content-Type': 'text/x-not-multipart', 'MIME-Version': '1.0'}
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']] (__end__, None, 3) with frequency once-per-instance
2019-07-22 11:54:37,532 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/cloud-config.txt - wb: [600] 0 bytes
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,532 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:37,532 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2019-07-22 11:54:37,532 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2019-07-22 11:54:37,533 - stages.py[DEBUG]: no vendordata from datasource
2019-07-22 11:54:37,533 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2019-07-22 11:54:37,533 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:37,533 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:37,533 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,543 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:37,543 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:37,543 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,545 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:37,545 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:37,545 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,548 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:37,548 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:37,548 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,549 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,549 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:37,549 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:37,549 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:37,549 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,549 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:37,550 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:37,550 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:37,550 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:37,550 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:37,552 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2019-07-22 11:54:37,552 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8520 bytes
2019-07-22 11:54:37,553 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2019-07-22 11:54:37,553 - main.py[DEBUG]: used datasource 'DataSourceEc2Local' from 'Ec2' was in di_report's list: ['Ec2', 'None']
2019-07-22 11:54:37,639 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:37,639 - stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2019-07-22 11:54:37,639 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2019-07-22 11:54:37,639 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7ff772909f60>)
2019-07-22 11:54:37,639 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2019-07-22 11:54:37,640 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2019-07-22 11:54:37,640 - stages.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2019-07-22 11:54:37,640 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2019-07-22 11:54:37,640 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_seed_random - wb: [644] 25 bytes
2019-07-22 11:54:37,641 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_seed_random'>)
2019-07-22 11:54:37,641 - cc_seed_random.py[DEBUG]: no command provided
2019-07-22 11:54:37,641 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2019-07-22 11:54:37,641 - stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2019-07-22 11:54:37,641 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2019-07-22 11:54:37,641 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7ff77290b898>)
2019-07-22 11:54:37,641 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2019-07-22 11:54:37,641 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2019-07-22 11:54:37,641 - stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2019-07-22 11:54:37,641 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2019-07-22 11:54:37,641 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_write_files - wb: [644] 25 bytes
2019-07-22 11:54:37,642 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_write_files'>)
2019-07-22 11:54:37,642 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2019-07-22 11:54:37,642 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2019-07-22 11:54:37,642 - stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2019-07-22 11:54:37,642 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2019-07-22 11:54:37,642 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7ff77290b128>)
2019-07-22 11:54:37,642 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'devices': ['/'], 'mode': 'auto'}
2019-07-22 11:54:37,643 - util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,659 - util.py[DEBUG]: Reading from /proc/1323/mountinfo (quiet=False)
2019-07-22 11:54:37,659 - util.py[DEBUG]: Read 2627 bytes from /proc/1323/mountinfo
2019-07-22 11:54:37,659 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,661 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,663 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,664 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:37,664 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:37,665 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:37,665 - util.py[DEBUG]: Read 971 bytes from /proc/self/status
2019-07-22 11:54:37,667 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:37,667 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:37,668 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2019-07-22 11:54:37,668 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2019-07-22 11:54:37,668 - util.py[DEBUG]: Reading from /sys/devices/vbd-768/block/xvda/dev (quiet=False)
2019-07-22 11:54:37,668 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-768/block/xvda/dev
2019-07-22 11:54:37,668 - util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,778 - util.py[DEBUG]: Running command ['growpart', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,835 - util.py[DEBUG]: resize_devices took 0.176 seconds
2019-07-22 11:54:37,835 - cc_growpart.py[INFO]: '/' resized: changed (/dev/xvda, 1) from 8588869120 to 32211189248
2019-07-22 11:54:37,836 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2019-07-22 11:54:37,836 - stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2019-07-22 11:54:37,836 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2019-07-22 11:54:37,836 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7ff77290b128>)
2019-07-22 11:54:37,836 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present
2019-07-22 11:54:37,836 - util.py[DEBUG]: Reading from /proc/1323/mountinfo (quiet=False)
2019-07-22 11:54:37,837 - util.py[DEBUG]: Read 2627 bytes from /proc/1323/mountinfo
2019-07-22 11:54:37,837 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2019-07-22 11:54:37,837 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,838 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,840 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,841 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:37,841 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:37,841 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:37,841 - util.py[DEBUG]: Read 972 bytes from /proc/self/status
2019-07-22 11:54:37,842 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
2019-07-22 11:54:37,842 - util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:37,885 - util.py[DEBUG]: Resizing took 0.044 seconds
2019-07-22 11:54:37,885 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2019-07-22 11:54:37,886 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2019-07-22 11:54:37,886 - stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2019-07-22 11:54:37,886 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2019-07-22 11:54:37,886 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_disk_setup - wb: [644] 25 bytes
2019-07-22 11:54:37,887 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_disk_setup'>)
2019-07-22 11:54:37,887 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2019-07-22 11:54:37,887 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2019-07-22 11:54:37,887 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2019-07-22 11:54:37,887 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_mounts - wb: [644] 24 bytes
2019-07-22 11:54:37,887 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_mounts'>)
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: mounts configuration is []
2019-07-22 11:54:37,888 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2019-07-22 11:54:37,888 - util.py[DEBUG]: Read 51 bytes from /etc/fstab
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2019-07-22 11:54:37,888 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: changed default device swap => None
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: no need to setup swap
2019-07-22 11:54:37,888 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2019-07-22 11:54:37,888 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2019-07-22 11:54:37,889 - stages.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2019-07-22 11:54:37,889 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2019-07-22 11:54:37,889 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_set_hostname - wb: [644] 24 bytes
2019-07-22 11:54:37,889 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_set_hostname'>)
2019-07-22 11:54:37,889 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:37,889 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:37,890 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:37,890 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2019-07-22 11:54:37,890 - stages.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2019-07-22 11:54:37,890 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2019-07-22 11:54:37,890 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7ff77290bf28>)
2019-07-22 11:54:37,890 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-0-235.eu-west-1.compute.internal (ip-10-0-0-235)
2019-07-22 11:54:37,890 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:37,890 - util.py[DEBUG]: Read 14 bytes from /etc/hostname
2019-07-22 11:54:37,890 - __init__.py[DEBUG]: Attempting to update hostname to ip-10-0-0-235 in 1 files
2019-07-22 11:54:37,890 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2019-07-22 11:54:37,890 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 14 bytes
2019-07-22 11:54:37,891 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2019-07-22 11:54:37,891 - stages.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2019-07-22 11:54:37,891 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2019-07-22 11:54:37,891 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7ff77290e940>)
2019-07-22 11:54:37,891 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2019-07-22 11:54:37,891 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2019-07-22 11:54:37,891 - stages.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2019-07-22 11:54:37,891 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2019-07-22 11:54:37,892 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ca_certs - wb: [644] 25 bytes
2019-07-22 11:54:37,892 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ca_certs'>)
2019-07-22 11:54:37,892 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca-certs' key in configuration
2019-07-22 11:54:37,892 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2019-07-22 11:54:37,892 - stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2019-07-22 11:54:37,892 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2019-07-22 11:54:37,893 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_rsyslog - wb: [644] 25 bytes
2019-07-22 11:54:37,893 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_rsyslog'>)
2019-07-22 11:54:37,893 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2019-07-22 11:54:37,893 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2019-07-22 11:54:37,893 - stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2019-07-22 11:54:37,893 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2019-07-22 11:54:37,893 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_users_groups - wb: [644] 25 bytes
2019-07-22 11:54:37,894 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_users_groups'>)
2019-07-22 11:54:37,894 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:37,894 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:37,895 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:37,895 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:37,895 - __init__.py[DEBUG]: Adding user ubuntu
2019-07-22 11:54:37,895 - util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2019-07-22 11:54:37,997 - util.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:38,019 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2019-07-22 11:54:38,019 - util.py[DEBUG]: Read 755 bytes from /etc/sudoers
2019-07-22 11:54:38,020 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 151 bytes
2019-07-22 11:54:38,021 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2019-07-22 11:54:38,021 - stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2019-07-22 11:54:38,021 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2019-07-22 11:54:38,021 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh - wb: [644] 24 bytes
2019-07-22 11:54:38,022 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh'>)
2019-07-22 11:54:38,023 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:38,120 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:38,153 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:38,155 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:38,160 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2019-07-22 11:54:38,161 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:38,161 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:38,162 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 448 bytes
2019-07-22 11:54:38,162 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2019-07-22 11:54:38,163 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2019-07-22 11:54:38,163 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:38,163 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:38,164 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 603 bytes
2019-07-22 11:54:38,164 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2019-07-22 11:54:38,164 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2019-07-22 11:54:38,164 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:38,165 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:38,165 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:38,165 - util.py[DEBUG]: cloud-init mode 'init' took 0.724 seconds (0.72)
2019-07-22 11:54:38,165 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2019-07-22 11:54:47,277 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:config' at Mon, 22 Jul 2019 11:54:47 +0000. Up 17.79 seconds.
2019-07-22 11:54:47,311 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:47,312 - stages.py[DEBUG]: Running module emit_upstart (<module 'cloudinit.config.cc_emit_upstart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_emit_upstart.py'>) with frequency always
2019-07-22 11:54:47,312 - handlers.py[DEBUG]: start: modules-config/config-emit_upstart: running config-emit_upstart with frequency always
2019-07-22 11:54:47,312 - helpers.py[DEBUG]: Running config-emit_upstart using lock (<cloudinit.helpers.DummyLock object at 0x7ff71073bac8>)
2019-07-22 11:54:47,312 - cc_emit_upstart.py[DEBUG]: no /sbin/initctl located
2019-07-22 11:54:47,312 - cc_emit_upstart.py[DEBUG]: not upstart system, 'emit_upstart' disabled
2019-07-22 11:54:47,312 - handlers.py[DEBUG]: finish: modules-config/config-emit_upstart: SUCCESS: config-emit_upstart ran successfully
2019-07-22 11:54:47,312 - stages.py[DEBUG]: Running module snap (<module 'cloudinit.config.cc_snap' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap.py'>) with frequency once-per-instance
2019-07-22 11:54:47,313 - handlers.py[DEBUG]: start: modules-config/config-snap: running config-snap with frequency once-per-instance
2019-07-22 11:54:47,313 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snap - wb: [644] 24 bytes
2019-07-22 11:54:47,313 - helpers.py[DEBUG]: Running config-snap using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snap'>)
2019-07-22 11:54:47,313 - cc_snap.py[DEBUG]: Skipping module named snap, no 'snap' key in configuration
2019-07-22 11:54:47,313 - handlers.py[DEBUG]: finish: modules-config/config-snap: SUCCESS: config-snap ran successfully
2019-07-22 11:54:47,313 - stages.py[DEBUG]: Running module snap_config (<module 'cloudinit.config.cc_snap_config' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap_config.py'>) with frequency once-per-instance
2019-07-22 11:54:47,314 - handlers.py[DEBUG]: start: modules-config/config-snap_config: running config-snap_config with frequency once-per-instance
2019-07-22 11:54:47,314 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snap_config - wb: [644] 24 bytes
2019-07-22 11:54:47,314 - helpers.py[DEBUG]: Running config-snap_config using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snap_config'>)
2019-07-22 11:54:47,314 - cc_snap_config.py[DEBUG]: No snappy config provided, skipping
2019-07-22 11:54:47,314 - handlers.py[DEBUG]: finish: modules-config/config-snap_config: SUCCESS: config-snap_config ran successfully
2019-07-22 11:54:47,314 - stages.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2019-07-22 11:54:47,314 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2019-07-22 11:54:47,315 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh_import_id - wb: [644] 25 bytes
2019-07-22 11:54:47,315 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh_import_id'>)
2019-07-22 11:54:47,315 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2019-07-22 11:54:47,315 - stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2019-07-22 11:54:47,315 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2019-07-22 11:54:47,316 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_locale - wb: [644] 25 bytes
2019-07-22 11:54:47,316 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_locale'>)
2019-07-22 11:54:47,316 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:47,316 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:47,316 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2019-07-22 11:54:47,316 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:47,316 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:47,316 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2019-07-22 11:54:47,316 - util.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:47,972 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2019-07-22 11:54:47,972 - util.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:48,097 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2019-07-22 11:54:48,097 - stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2019-07-22 11:54:48,098 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2019-07-22 11:54:48,098 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_set_passwords - wb: [644] 25 bytes
2019-07-22 11:54:48,098 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_set_passwords'>)
2019-07-22 11:54:48,099 - cc_set_passwords.py[DEBUG]: Leaving ssh config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2019-07-22 11:54:48,099 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2019-07-22 11:54:48,099 - stages.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2019-07-22 11:54:48,099 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2019-07-22 11:54:48,099 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_grub_dpkg - wb: [644] 25 bytes
2019-07-22 11:54:48,099 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_grub_dpkg'>)
2019-07-22 11:54:48,099 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/xvda','false'
2019-07-22 11:54:48,099 - util.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,409 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2019-07-22 11:54:48,409 - stages.py[DEBUG]: Running module apt-pipelining (<module 'cloudinit.config.cc_apt_pipelining' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_pipelining.py'>) with frequency once-per-instance
2019-07-22 11:54:48,410 - handlers.py[DEBUG]: start: modules-config/config-apt-pipelining: running config-apt-pipelining with frequency once-per-instance
2019-07-22 11:54:48,410 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_apt_pipelining - wb: [644] 25 bytes
2019-07-22 11:54:48,410 - helpers.py[DEBUG]: Running config-apt-pipelining using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_apt_pipelining'>)
2019-07-22 11:54:48,411 - util.py[DEBUG]: Writing to /etc/apt/apt.conf.d/90cloud-init-pipelining - wb: [644] 80 bytes
2019-07-22 11:54:48,412 - cc_apt_pipelining.py[DEBUG]: Wrote /etc/apt/apt.conf.d/90cloud-init-pipelining with apt pipeline depth setting 0
2019-07-22 11:54:48,413 - handlers.py[DEBUG]: finish: modules-config/config-apt-pipelining: SUCCESS: config-apt-pipelining ran successfully
2019-07-22 11:54:48,413 - stages.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2019-07-22 11:54:48,413 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2019-07-22 11:54:48,413 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_apt_configure - wb: [644] 24 bytes
2019-07-22 11:54:48,413 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_apt_configure'>)
2019-07-22 11:54:48,413 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2019-07-22 11:54:48,413 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:48,413 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:48,414 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:48,414 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:48,414 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2019-07-22 11:54:48,414 - util.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,466 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,468 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2019-07-22 11:54:48,468 - cc_apt_configure.py[DEBUG]: got security mirror: None
2019-07-22 11:54:48,469 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,498 - util.py[DEBUG]: Resolving URL: http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ took 0.027 seconds
2019-07-22 11:54:48,498 - __init__.py[DEBUG]: filtered distro mirror info: {'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'security': 'http://security.ubuntu.com/ubuntu'}
2019-07-22 11:54:48,498 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'MIRROR': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/'}
2019-07-22 11:54:48,498 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2019-07-22 11:54:48,499 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.tmpl (quiet=False)
2019-07-22 11:54:48,499 - util.py[DEBUG]: Read 2841 bytes from /etc/cloud/templates/sources.list.ubuntu.tmpl
2019-07-22 11:54:48,506 - util.py[DEBUG]: Writing to /etc/apt/sources.list - wb: [644] 3335 bytes
2019-07-22 11:54:48,506 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,550 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en
2019-07-22 11:54:48,550 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages
2019-07-22 11:54:48,550 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_InRelease
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages
2019-07-22 11:54:48,551 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages
2019-07-22 11:54:48,551 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2019-07-22 11:54:48,551 - stages.py[DEBUG]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) with frequency once-per-instance
2019-07-22 11:54:48,551 - handlers.py[DEBUG]: start: modules-config/config-ubuntu-advantage: running config-ubuntu-advantage with frequency once-per-instance
2019-07-22 11:54:48,552 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ubuntu_advantage - wb: [644] 25 bytes
2019-07-22 11:54:48,552 - helpers.py[DEBUG]: Running config-ubuntu-advantage using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ubuntu_advantage'>)
2019-07-22 11:54:48,552 - cc_ubuntu_advantage.py[DEBUG]: Skipping module named ubuntu-advantage, no 'ubuntu-advantage' key in configuration
2019-07-22 11:54:48,552 - handlers.py[DEBUG]: finish: modules-config/config-ubuntu-advantage: SUCCESS: config-ubuntu-advantage ran successfully
2019-07-22 11:54:48,552 - stages.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2019-07-22 11:54:48,552 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2019-07-22 11:54:48,553 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ntp - wb: [644] 24 bytes
2019-07-22 11:54:48,553 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ntp'>)
2019-07-22 11:54:48,553 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2019-07-22 11:54:48,553 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2019-07-22 11:54:48,553 - stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2019-07-22 11:54:48,553 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2019-07-22 11:54:48,553 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_timezone - wb: [644] 25 bytes
2019-07-22 11:54:48,554 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_timezone'>)
2019-07-22 11:54:48,554 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2019-07-22 11:54:48,554 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2019-07-22 11:54:48,554 - stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2019-07-22 11:54:48,554 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2019-07-22 11:54:48,554 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7ff71073b940>)
2019-07-22 11:54:48,554 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2019-07-22 11:54:48,554 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2019-07-22 11:54:48,554 - stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2019-07-22 11:54:48,555 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2019-07-22 11:54:48,555 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_runcmd - wb: [644] 25 bytes
2019-07-22 11:54:48,555 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_runcmd'>)
2019-07-22 11:54:48,555 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2019-07-22 11:54:48,555 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2019-07-22 11:54:48,555 - stages.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2019-07-22 11:54:48,555 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2019-07-22 11:54:48,556 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_byobu - wb: [644] 25 bytes
2019-07-22 11:54:48,556 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_byobu'>)
2019-07-22 11:54:48,556 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2019-07-22 11:54:48,556 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2019-07-22 11:54:48,556 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:48,557 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:48,557 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:48,557 - util.py[DEBUG]: cloud-init mode 'modules' took 1.326 seconds (1.32)
2019-07-22 11:54:48,557 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2019-07-22 11:54:48,853 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:final' at Mon, 22 Jul 2019 11:54:48 +0000. Up 19.36 seconds.
2019-07-22 11:54:48,894 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:48,895 - stages.py[DEBUG]: Running module snappy (<module 'cloudinit.config.cc_snappy' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snappy.py'>) with frequency once-per-instance
2019-07-22 11:54:48,895 - handlers.py[DEBUG]: start: modules-final/config-snappy: running config-snappy with frequency once-per-instance
2019-07-22 11:54:48,895 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snappy - wb: [644] 25 bytes
2019-07-22 11:54:48,895 - helpers.py[DEBUG]: Running config-snappy using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_snappy'>)
2019-07-22 11:54:48,896 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:48,896 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:48,896 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:48,896 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:48,896 - cc_snappy.py[DEBUG]: snappy: 'auto' mode, and system not snappy
2019-07-22 11:54:48,897 - handlers.py[DEBUG]: finish: modules-final/config-snappy: SUCCESS: config-snappy ran successfully
2019-07-22 11:54:48,897 - stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance
2019-07-22 11:54:48,897 - handlers.py[DEBUG]: start: modules-final/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
2019-07-22 11:54:48,897 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_package_update_upgrade_install - wb: [644] 24 bytes
2019-07-22 11:54:48,897 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_package_update_upgrade_install'>)
2019-07-22 11:54:48,897 - handlers.py[DEBUG]: finish: modules-final/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
2019-07-22 11:54:48,897 - stages.py[DEBUG]: Running module fan (<module 'cloudinit.config.cc_fan' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_fan.py'>) with frequency once-per-instance
2019-07-22 11:54:48,898 - handlers.py[DEBUG]: start: modules-final/config-fan: running config-fan with frequency once-per-instance
2019-07-22 11:54:48,898 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_fan - wb: [644] 24 bytes
2019-07-22 11:54:48,898 - helpers.py[DEBUG]: Running config-fan using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_fan'>)
2019-07-22 11:54:48,898 - cc_fan.py[DEBUG]: fan: no 'fan' config entry. disabling
2019-07-22 11:54:48,898 - handlers.py[DEBUG]: finish: modules-final/config-fan: SUCCESS: config-fan ran successfully
2019-07-22 11:54:48,898 - stages.py[DEBUG]: Running module landscape (<module 'cloudinit.config.cc_landscape' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_landscape.py'>) with frequency once-per-instance
2019-07-22 11:54:48,899 - handlers.py[DEBUG]: start: modules-final/config-landscape: running config-landscape with frequency once-per-instance
2019-07-22 11:54:48,899 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_landscape - wb: [644] 25 bytes
2019-07-22 11:54:48,899 - helpers.py[DEBUG]: Running config-landscape using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_landscape'>)
2019-07-22 11:54:48,899 - handlers.py[DEBUG]: finish: modules-final/config-landscape: SUCCESS: config-landscape ran successfully
2019-07-22 11:54:48,899 - stages.py[DEBUG]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) with frequency once-per-instance
2019-07-22 11:54:48,899 - handlers.py[DEBUG]: start: modules-final/config-lxd: running config-lxd with frequency once-per-instance
2019-07-22 11:54:48,900 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_lxd - wb: [644] 25 bytes
2019-07-22 11:54:48,900 - helpers.py[DEBUG]: Running config-lxd using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_lxd'>)
2019-07-22 11:54:48,900 - cc_lxd.py[DEBUG]: Skipping module named lxd, not present or disabled by cfg
2019-07-22 11:54:48,900 - handlers.py[DEBUG]: finish: modules-final/config-lxd: SUCCESS: config-lxd ran successfully
2019-07-22 11:54:48,900 - stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_puppet.py'>) with frequency once-per-instance
2019-07-22 11:54:48,900 - handlers.py[DEBUG]: start: modules-final/config-puppet: running config-puppet with frequency once-per-instance
2019-07-22 11:54:48,901 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_puppet - wb: [644] 25 bytes
2019-07-22 11:54:48,901 - helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_puppet'>)
2019-07-22 11:54:48,901 - cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
2019-07-22 11:54:48,901 - handlers.py[DEBUG]: finish: modules-final/config-puppet: SUCCESS: config-puppet ran successfully
2019-07-22 11:54:48,901 - stages.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py'>) with frequency once-per-instance
2019-07-22 11:54:48,901 - handlers.py[DEBUG]: start: modules-final/config-chef: running config-chef with frequency once-per-instance
2019-07-22 11:54:48,901 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_chef - wb: [644] 25 bytes
2019-07-22 11:54:48,902 - helpers.py[DEBUG]: Running config-chef using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_chef'>)
2019-07-22 11:54:48,902 - cc_chef.py[DEBUG]: Skipping module named chef, no 'chef' key in configuration
2019-07-22 11:54:48,902 - handlers.py[DEBUG]: finish: modules-final/config-chef: SUCCESS: config-chef ran successfully
2019-07-22 11:54:48,902 - stages.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mcollective.py'>) with frequency once-per-instance
2019-07-22 11:54:48,902 - handlers.py[DEBUG]: start: modules-final/config-mcollective: running config-mcollective with frequency once-per-instance
2019-07-22 11:54:48,902 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_mcollective - wb: [644] 25 bytes
2019-07-22 11:54:48,903 - helpers.py[DEBUG]: Running config-mcollective using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_mcollective'>)
2019-07-22 11:54:48,903 - cc_mcollective.py[DEBUG]: Skipping module named mcollective, no 'mcollective' key in configuration
2019-07-22 11:54:48,903 - handlers.py[DEBUG]: finish: modules-final/config-mcollective: SUCCESS: config-mcollective ran successfully
2019-07-22 11:54:48,903 - stages.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_salt_minion.py'>) with frequency once-per-instance
2019-07-22 11:54:48,903 - handlers.py[DEBUG]: start: modules-final/config-salt-minion: running config-salt-minion with frequency once-per-instance
2019-07-22 11:54:48,903 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_salt_minion - wb: [644] 25 bytes
2019-07-22 11:54:48,903 - helpers.py[DEBUG]: Running config-salt-minion using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_salt_minion'>)
2019-07-22 11:54:48,903 - cc_salt_minion.py[DEBUG]: Skipping module named salt-minion, no 'salt_minion' key in configuration
2019-07-22 11:54:48,903 - handlers.py[DEBUG]: finish: modules-final/config-salt-minion: SUCCESS: config-salt-minion ran successfully
2019-07-22 11:54:48,904 - stages.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2019-07-22 11:54:48,904 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2019-07-22 11:54:48,904 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_rightscale_userdata - wb: [644] 25 bytes
2019-07-22 11:54:48,904 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_rightscale_userdata'>)
2019-07-22 11:54:48,904 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2019-07-22 11:54:48,904 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2019-07-22 11:54:48,904 - stages.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2019-07-22 11:54:48,904 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2019-07-22 11:54:48,905 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_vendor - wb: [644] 25 bytes
2019-07-22 11:54:48,905 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_vendor'>)
2019-07-22 11:54:48,905 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2019-07-22 11:54:48,905 - stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2019-07-22 11:54:48,905 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2019-07-22 11:54:48,905 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2019-07-22 11:54:48,906 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2019-07-22 11:54:48,906 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2019-07-22 11:54:48,906 - stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2019-07-22 11:54:48,906 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2019-07-22 11:54:48,906 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f6ca76422e8>)
2019-07-22 11:54:48,906 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2019-07-22 11:54:48,906 - stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2019-07-22 11:54:48,907 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2019-07-22 11:54:48,907 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_per_instance - wb: [644] 25 bytes
2019-07-22 11:54:48,907 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_per_instance'>)
2019-07-22 11:54:48,907 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2019-07-22 11:54:48,907 - stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2019-07-22 11:54:48,907 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2019-07-22 11:54:48,908 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_user - wb: [644] 25 bytes
2019-07-22 11:54:48,908 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_scripts_user'>)
2019-07-22 11:54:48,908 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2019-07-22 11:54:48,908 - stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2019-07-22 11:54:48,908 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2019-07-22 11:54:48,908 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2019-07-22 11:54:48,909 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_ssh_authkey_fingerprints'>)
2019-07-22 11:54:48,909 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:48,909 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:48,909 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2019-07-22 11:54:48,909 - util.py[DEBUG]: Read 448 bytes from /home/ubuntu/.ssh/authorized_keys
2019-07-22 11:54:48,933 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2019-07-22 11:54:48,933 - stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2019-07-22 11:54:48,933 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2019-07-22 11:54:48,933 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_keys_to_console - wb: [644] 25 bytes
2019-07-22 11:54:48,933 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_keys_to_console'>)
2019-07-22 11:54:48,933 - util.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:48,961 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2019-07-22 11:54:48,961 - stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2019-07-22 11:54:48,962 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2019-07-22 11:54:48,962 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_phone_home - wb: [644] 25 bytes
2019-07-22 11:54:48,962 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_phone_home'>)
2019-07-22 11:54:48,962 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2019-07-22 11:54:48,963 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2019-07-22 11:54:48,963 - stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2019-07-22 11:54:48,963 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2019-07-22 11:54:48,963 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f6ca6eb0198>)
2019-07-22 11:54:48,963 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:48,963 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:48,966 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 finished at Mon, 22 Jul 2019 11:54:48 +0000. Datasource DataSourceEc2Local.  Up 19.52 seconds
2019-07-22 11:54:48,966 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 79 bytes
2019-07-22 11:54:48,966 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2019-07-22 11:54:48,966 - stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2019-07-22 11:54:48,967 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2019-07-22 11:54:48,967 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_power_state_change - wb: [644] 25 bytes
2019-07-22 11:54:48,967 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0552f5d9cc06a76fd/sem/config_power_state_change'>)
2019-07-22 11:54:48,967 - cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
2019-07-22 11:54:48,967 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2019-07-22 11:54:48,967 - main.py[DEBUG]: Ran 20 modules with 0 failures
2019-07-22 11:54:48,968 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2019-07-22 11:54:48,968 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:48,968 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:48,968 - util.py[DEBUG]: cloud-init mode 'modules' took 0.162 seconds (0.17)
2019-07-22 11:54:48,968 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
