2019-07-22 11:54:22,235 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init-local' at Mon, 22 Jul 2019 11:54:22 +0000. Up 6.72 seconds.
2019-07-22 11:54:22,235 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:22,235 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:22,238 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:22,239 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:22,239 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2019-07-22 11:54:22,239 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
2019-07-22 11:54:22,239 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2019-07-22 11:54:22,239 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:22,239 - stages.py[DEBUG]: no cache found
2019-07-22 11:54:22,239 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2019-07-22 11:54:22,239 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:22,243 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:22,243 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2019-07-22 11:54:22,281 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:22,281 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:22,317 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceOpenStackLocal', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceEc2Local']
2019-07-22 11:54:22,317 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2019-07-22 11:54:22,317 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2019-07-22 11:54:22,317 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,317 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,319 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,321 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,322 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,323 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:22,323 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec253960-b488-5527-e8bb-75d1f35810df
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2019-07-22 11:54:22,323 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2019-07-22 11:54:22,324 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2019-07-22 11:54:22,324 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,325 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,327 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,340 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,352 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,364 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: no local data found from DataSourceNoCloud
2019-07-22 11:54:22,365 - handlers.py[DEBUG]: start: init-local/search-ConfigDrive: searching for local data from DataSourceConfigDrive
2019-07-22 11:54:22,365 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceConfigDrive.DataSourceConfigDrive'>
2019-07-22 11:54:22,365 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,365 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,367 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,368 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,369 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,371 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,383 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,394 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=config-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,406 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONFIG-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,418 - DataSourceConfigDrive.py[DEBUG]: devices=[] dslist=['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None']
2019-07-22 11:54:22,418 - handlers.py[DEBUG]: finish: init-local/search-ConfigDrive: SUCCESS: no local data found from DataSourceConfigDrive
2019-07-22 11:54:22,418 - handlers.py[DEBUG]: start: init-local/search-OpenNebula: searching for local data from DataSourceOpenNebula
2019-07-22 11:54:22,418 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenNebula.DataSourceOpenNebula'>
2019-07-22 11:54:22,418 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,418 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONTEXT', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,430 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CDROM', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,442 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,454 - handlers.py[DEBUG]: finish: init-local/search-OpenNebula: SUCCESS: no local data found from DataSourceOpenNebula
2019-07-22 11:54:22,454 - handlers.py[DEBUG]: start: init-local/search-DigitalOcean: searching for local data from DataSourceDigitalOcean
2019-07-22 11:54:22,454 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceDigitalOcean.DataSourceDigitalOcean'>
2019-07-22 11:54:22,455 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,455 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,456 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,457 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,459 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,459 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,459 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,459 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,459 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:22,460 - util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
2019-07-22 11:54:22,460 - util.py[DEBUG]: Read 4 bytes from /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:22,460 - util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Xen
2019-07-22 11:54:22,460 - handlers.py[DEBUG]: finish: init-local/search-DigitalOcean: SUCCESS: no local data found from DataSourceDigitalOcean
2019-07-22 11:54:22,460 - handlers.py[DEBUG]: start: init-local/search-Azure: searching for local data from DataSourceAzure
2019-07-22 11:54:22,460 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'>
2019-07-22 11:54:22,460 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,460 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,462 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,463 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,465 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,465 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,465 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,465 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,465 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:22,465 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:22,466 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:22,466 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:22,466 - DataSourceAzure.py[DEBUG]: Non-Azure DMI asset tag '' discovered.
2019-07-22 11:54:22,466 - handlers.py[DEBUG]: finish: init-local/search-Azure: SUCCESS: no local data found from DataSourceAzure
2019-07-22 11:54:22,466 - handlers.py[DEBUG]: start: init-local/search-OVF: searching for local data from DataSourceOVF
2019-07-22 11:54:22,466 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'>
2019-07-22 11:54:22,466 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,466 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,468 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,469 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,471 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,471 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,471 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,471 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,471 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:22,471 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:22,471 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:22,471 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:22,472 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2019-07-22 11:54:22,472 - util.py[DEBUG]: Read 1991 bytes from /proc/mounts
2019-07-22 11:54:22,472 - util.py[DEBUG]: Fetched {'securityfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs', 'mountpoint': '/sys/kernel/security'}, 'cgroup': {'opts': 'rw,nosuid,nodev,noexec,relatime,pids', 'fstype': 'cgroup', 'mountpoint': '/sys/fs/cgroup/pids'}, 'sysfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs', 'mountpoint': '/sys'}, '/dev/xvda1': {'opts': 'rw,relatime,discard,data=ordered', 'fstype': 'ext4', 'mountpoint': '/'}, 'systemd-1': {'opts': 'rw,relatime,fd=22,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'fstype': 'autofs', 'mountpoint': '/proc/sys/fs/binfmt_misc'}, 'debugfs': {'opts': 'rw,relatime', 'fstype': 'debugfs', 'mountpoint': '/sys/kernel/debug'}, 'hugetlbfs': {'opts': 'rw,relatime', 'fstype': 'hugetlbfs', 'mountpoint': '/dev/hugepages'}, 'devpts': {'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts', 'mountpoint': '/dev/pts'}, 'udev': {'opts': 'rw,nosuid,relatime,size=30907648k,nr_inodes=7726912,mode=755', 'fstype': 'devtmpfs', 'mountpoint': '/dev'}, 'tmpfs': {'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs', 'mountpoint': '/sys/fs/cgroup'}, 'fusectl': {'opts': 'rw,relatime', 'fstype': 'fusectl', 'mountpoint': '/sys/fs/fuse/connections'}, 'proc': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc', 'mountpoint': '/proc'}, 'pstore': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore', 'mountpoint': '/sys/fs/pstore'}, 'mqueue': {'opts': 'rw,relatime', 'fstype': 'mqueue', 'mountpoint': '/dev/mqueue'}} mounts from proc
2019-07-22 11:54:22,472 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:22,484 - handlers.py[DEBUG]: finish: init-local/search-OVF: SUCCESS: no local data found from DataSourceOVF
2019-07-22 11:54:22,484 - handlers.py[DEBUG]: start: init-local/search-OpenStackLocal: searching for local data from DataSourceOpenStackLocal
2019-07-22 11:54:22,484 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenStack.DataSourceOpenStackLocal'>
2019-07-22 11:54:22,484 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,484 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,486 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,487 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,489 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,489 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,489 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,490 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,490 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:22,490 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:22,490 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:22,490 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:22,490 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,492 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,493 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,495 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,495 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,495 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,495 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,495 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:22,495 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:22,495 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:22,496 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:22,496 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,496 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,496 - handlers.py[DEBUG]: finish: init-local/search-OpenStackLocal: SUCCESS: no local data found from DataSourceOpenStackLocal
2019-07-22 11:54:22,496 - handlers.py[DEBUG]: start: init-local/search-CloudSigma: searching for local data from DataSourceCloudSigma
2019-07-22 11:54:22,496 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceCloudSigma.DataSourceCloudSigma'>
2019-07-22 11:54:22,496 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,496 - DataSourceCloudSigma.py[DEBUG]: determining hypervisor product name via dmi data
2019-07-22 11:54:22,496 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,498 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,499 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,501 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,501 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,501 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,501 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,501 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:22,501 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:22,502 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:22,502 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:22,502 - DataSourceCloudSigma.py[DEBUG]: detected hypervisor as HVM domU
2019-07-22 11:54:22,502 - handlers.py[DEBUG]: finish: init-local/search-CloudSigma: SUCCESS: no local data found from DataSourceCloudSigma
2019-07-22 11:54:22,502 - handlers.py[DEBUG]: start: init-local/search-SmartOS: searching for local data from DataSourceSmartOS
2019-07-22 11:54:22,502 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceSmartOS.DataSourceSmartOS'>
2019-07-22 11:54:22,502 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,504 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,506 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,507 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,507 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,507 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,508 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,508 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:22,508 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:22,508 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:22,508 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:22,508 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,508 - DataSourceSmartOS.py[DEBUG]: Not running on smartos
2019-07-22 11:54:22,508 - handlers.py[DEBUG]: finish: init-local/search-SmartOS: SUCCESS: no local data found from DataSourceSmartOS
2019-07-22 11:54:22,508 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2019-07-22 11:54:22,508 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2019-07-22 11:54:22,508 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:22,508 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2019-07-22 11:54:22,508 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2019-07-22 11:54:22,508 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,510 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,512 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,513 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:22,513 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:22,513 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:22,514 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:22,514 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:22,514 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:22,514 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:22,514 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec253960-b488-5527-e8bb-75d1f35810df
2019-07-22 11:54:22,514 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_platform=AWS
2019-07-22 11:54:22,514 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:22,514 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:22,515 - util.py[DEBUG]: Reading from /sys/class/net/ens3/name_assign_type (quiet=False)
2019-07-22 11:54:22,515 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/name_assign_type
2019-07-22 11:54:22,515 - util.py[DEBUG]: Reading from /sys/class/net/ens3/carrier (quiet=False)
2019-07-22 11:54:22,515 - util.py[DEBUG]: Reading from /sys/class/net/ens3/dormant (quiet=False)
2019-07-22 11:54:22,515 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:22,515 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:22,515 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:22,515 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:22,516 - dhcp.py[DEBUG]: Performing a dhcp discovery on ens3
2019-07-22 11:54:22,516 - util.py[DEBUG]: Copying /sbin/dhclient to /var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient
2019-07-22 11:54:22,519 - util.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,540 - util.py[DEBUG]: Running command ['/var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient.pid', 'ens3', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,580 - util.py[DEBUG]: All files appeared after 0 seconds: ['/var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient.pid', '/var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhcp.leases']
2019-07-22 11:54:22,580 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient.pid (quiet=False)
2019-07-22 11:54:22,580 - util.py[DEBUG]: Read 5 bytes from /var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhclient.pid
2019-07-22 11:54:22,580 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhcp.leases (quiet=False)
2019-07-22 11:54:22,580 - util.py[DEBUG]: Read 513 bytes from /var/tmp/cloud-init/cloud-init-dhcp-goaog8m2/dhcp.leases
2019-07-22 11:54:22,580 - dhcp.py[DEBUG]: Received dhcp lease on ens3 for 10.0.0.233/255.255.255.0
2019-07-22 11:54:22,581 - __init__.py[DEBUG]: Attempting setup of ephemeral network on ens3 with 10.0.0.233/24 brd 10.0.0.255
2019-07-22 11:54:22,581 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '10.0.0.233/24', 'broadcast', '10.0.0.255', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,582 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,585 - util.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,587 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', 'default', 'via', '10.0.0.1', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,592 - util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.004 seconds
2019-07-22 11:54:22,592 - util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.000 seconds
2019-07-22 11:54:22,592 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2019-07-22 11:54:22,593 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2009-04-04/meta-data/instance-id' with {'url': 'http://169.254.169.254/2009-04-04/meta-data/instance-id', 'allow_redirects': True, 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,598 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2009-04-04/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:22,598 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2019-07-22 11:54:22,598 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,600 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:22,600 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
2019-07-22 11:54:22,600 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,601 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,603 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 268b) after 1 attempts
2019-07-22 11:54:22,603 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,605 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 30b) after 1 attempts
2019-07-22 11:54:22,605 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,606 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
2019-07-22 11:54:22,606 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,608 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0 (200, 3b) after 1 attempts
2019-07-22 11:54:22,608 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,609 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1 (200, 3b) after 1 attempts
2019-07-22 11:54:22,609 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,611 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2019-07-22 11:54:22,611 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,612 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/ (200, 26b) after 1 attempts
2019-07-22 11:54:22,613 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/info' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/info', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,614 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/info (200, 245b) after 1 attempts
2019-07-22 11:54:22,614 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,616 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
2019-07-22 11:54:22,616 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,617 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2019-07-22 11:54:22,617 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,619 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
2019-07-22 11:54:22,619 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,620 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2019-07-22 11:54:22,621 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,622 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2019-07-22 11:54:22,622 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,624 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ (200, 230b) after 1 attempts
2019-07-22 11:54:22,624 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,625 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/ (200, 14b) after 1 attempts
2019-07-22 11:54:22,626 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/34.254.238.234' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/34.254.238.234', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,628 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/ipv4-associations/34.254.238.234 (200, 10b) after 1 attempts
2019-07-22 11:54:22,628 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/device-number', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,629 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/device-number (200, 1b) after 1 attempts
2019-07-22 11:54:22,630 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/mac', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,631 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/mac (200, 17b) after 1 attempts
2019-07-22 11:54:22,631 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-ipv4-cidr-block', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,633 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:22,633 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/interface-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,634 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/interface-id (200, 21b) after 1 attempts
2019-07-22 11:54:22,635 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-hostname', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,637 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:22,637 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/owner-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,638 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/owner-id (200, 12b) after 1 attempts
2019-07-22 11:54:22,638 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-hostname', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,640 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-hostname (200, 50b) after 1 attempts
2019-07-22 11:54:22,640 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-group-ids', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,643 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-group-ids (200, 20b) after 1 attempts
2019-07-22 11:54:22,643 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-groups', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,644 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:22,645 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,646 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-id (200, 21b) after 1 attempts
2019-07-22 11:54:22,646 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,648 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/subnet-id (200, 24b) after 1 attempts
2019-07-22 11:54:22,648 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,650 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
2019-07-22 11:54:22,650 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-ipv4s', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,652 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/public-ipv4s (200, 14b) after 1 attempts
2019-07-22 11:54:22,652 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-ipv4s', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,653 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/local-ipv4s (200, 10b) after 1 attempts
2019-07-22 11:54:22,654 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-block', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,655 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:30:8c:18:cb:9e/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:22,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,657 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
2019-07-22 11:54:22,657 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,658 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2019-07-22 11:54:22,659 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,660 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 68b) after 1 attempts
2019-07-22 11:54:22,660 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,662 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 448b) after 1 attempts
2019-07-22 11:54:22,662 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,664 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
2019-07-22 11:54:22,664 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,666 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
2019-07-22 11:54:22,666 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,667 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
2019-07-22 11:54:22,667 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,669 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
2019-07-22 11:54:22,669 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,671 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
2019-07-22 11:54:22,671 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,672 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
2019-07-22 11:54:22,673 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,674 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2019-07-22 11:54:22,674 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,676 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
2019-07-22 11:54:22,676 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,678 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:22,678 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,679 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 10b) after 1 attempts
2019-07-22 11:54:22,680 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,681 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:22,681 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:22,683 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,685 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
2019-07-22 11:54:22,685 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,687 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 50b) after 1 attempts
2019-07-22 11:54:22,687 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,688 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 10b) after 1 attempts
2019-07-22 11:54:22,688 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,690 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 14b) after 1 attempts
2019-07-22 11:54:22,690 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,692 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 40b) after 1 attempts
2019-07-22 11:54:22,692 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,694 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
2019-07-22 11:54:22,694 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,696 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
2019-07-22 11:54:22,697 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,698 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
2019-07-22 11:54:22,698 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,700 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2019-07-22 11:54:22,700 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,701 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
2019-07-22 11:54:22,702 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'allow_redirects': True, 'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'method': 'GET'} configuration
2019-07-22 11:54:22,703 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
2019-07-22 11:54:22,703 - util.py[DEBUG]: Crawl of metadata service took 0.115 seconds
2019-07-22 11:54:22,703 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', 'default', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,705 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'down'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,740 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '10.0.0.233/24', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,744 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2019-07-22 11:54:22,744 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2019-07-22 11:54:22,744 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:22,744 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:22,744 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,755 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:22,755 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:22,755 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,756 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:22,756 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:22,756 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,760 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:22,760 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:22,760 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,760 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,760 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:22,761 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:22,761 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-05b3c198c7419b4f8'
2019-07-22 11:54:22,762 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-05b3c198c7419b4f8/datasource (quiet=False)
2019-07-22 11:54:22,762 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/datasource - wb: [644] 39 bytes
2019-07-22 11:54:22,762 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:22,763 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:22,763 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2019-07-22 11:54:22,763 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:22,763 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:22,763 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2019-07-22 11:54:22,764 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9136 bytes
2019-07-22 11:54:22,765 - main.py[DEBUG]: [local] init will now be targeting instance id: i-05b3c198c7419b4f8. new=True
2019-07-22 11:54:22,765 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:22,765 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:22,765 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,775 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:22,775 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:22,775 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,777 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:22,777 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:22,777 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,780 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:22,780 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:22,780 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,780 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:22,781 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:22,781 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:22,782 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-0-233.eu-west-1.compute.internal (ip-10-0-0-233)
2019-07-22 11:54:22,782 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:22,782 - util.py[DEBUG]: Read 7 bytes from /etc/hostname
2019-07-22 11:54:22,782 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 14 bytes
2019-07-22 11:54:22,783 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-10-0-0-233
2019-07-22 11:54:22,783 - util.py[DEBUG]: Running command ['hostname', 'ip-10-0-0-233'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,786 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:22,786 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:22,786 - stages.py[DEBUG]: applying net config names for {'config': [{'subnets': [{'type': 'dhcp4'}], 'name': 'ens3', 'type': 'physical', 'mac_address': '02:30:8c:18:cb:9e'}], 'version': 1}
2019-07-22 11:54:22,786 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:22,786 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:22,786 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:22,787 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:22,787 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:22,788 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:22,788 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:22,788 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:22,788 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,791 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:22,793 - __init__.py[DEBUG]: no work necessary for renaming of [['02:30:8c:18:cb:9e', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:22,793 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'config': [{'subnets': [{'type': 'dhcp4'}], 'name': 'ens3', 'type': 'physical', 'mac_address': '02:30:8c:18:cb:9e'}], 'version': 1}
2019-07-22 11:54:22,793 - __init__.py[DEBUG]: Selected renderer 'eni' from priority list: None
2019-07-22 11:54:22,795 - util.py[DEBUG]: Writing to /etc/network/interfaces.d/50-cloud-init.cfg - wb: [644] 367 bytes
2019-07-22 11:54:22,796 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 96 bytes
2019-07-22 11:54:22,796 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2019-07-22 11:54:22,797 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:22,797 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:22,797 - util.py[DEBUG]: cloud-init mode 'init' took 0.591 seconds (0.59)
2019-07-22 11:54:22,797 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2019-07-22 11:54:23,294 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init' at Mon, 22 Jul 2019 11:54:23 +0000. Up 7.78 seconds.
2019-07-22 11:54:23,294 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:23,294 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:23,296 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:23,297 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:23,297 - util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,300 - util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,302 - util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2019-07-22 11:54:23,304 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
2019-07-22 11:54:23,305 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
2019-07-22 11:54:23,305 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2019-07-22 11:54:23,305 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:23,305 - util.py[DEBUG]: Read 9136 bytes from /var/lib/cloud/instance/obj.pkl
2019-07-22 11:54:23,307 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2019-07-22 11:54:23,307 - util.py[DEBUG]: Read 20 bytes from /run/cloud-init/.instance-id
2019-07-22 11:54:23,307 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:23,307 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:23,308 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:23,308 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:23,308 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,319 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:23,319 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:23,319 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,320 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:23,320 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:23,320 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,324 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:23,324 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:23,324 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,324 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,324 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:23,325 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:23,325 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-05b3c198c7419b4f8'
2019-07-22 11:54:23,325 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-05b3c198c7419b4f8/datasource (quiet=False)
2019-07-22 11:54:23,325 - util.py[DEBUG]: Read 39 bytes from /var/lib/cloud/instances/i-05b3c198c7419b4f8/datasource
2019-07-22 11:54:23,325 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/datasource - wb: [644] 39 bytes
2019-07-22 11:54:23,326 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:23,326 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:23,326 - util.py[DEBUG]: Read 20 bytes from /var/lib/cloud/data/instance-id
2019-07-22 11:54:23,326 - stages.py[DEBUG]: previous iid found to be i-05b3c198c7419b4f8
2019-07-22 11:54:23,326 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:23,327 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:23,327 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2019-07-22 11:54:23,328 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9206 bytes
2019-07-22 11:54:23,328 - main.py[DEBUG]: [net] init will now be targeting instance id: i-05b3c198c7419b4f8. new=False
2019-07-22 11:54:23,328 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:23,328 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:23,328 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,339 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:23,339 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:23,339 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,340 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:23,340 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:23,340 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,343 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:23,343 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:23,344 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,344 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,344 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:23,345 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:23,345 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:23,345 - stages.py[DEBUG]: applying net config names for {'config': [{'mac_address': '02:30:8c:18:cb:9e', 'name': 'ens3', 'type': 'physical', 'subnets': [{'type': 'dhcp4'}]}], 'version': 1}
2019-07-22 11:54:23,346 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:23,346 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:23,346 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:23,346 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:23,346 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:23,346 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:23,347 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:23,347 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:23,347 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:23,347 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:23,347 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:23,347 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:23,347 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,349 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,351 - __init__.py[DEBUG]: no work necessary for renaming of [['02:30:8c:18:cb:9e', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:23,351 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
2019-07-22 11:54:23,352 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2019-07-22 11:54:23,352 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2019-07-22 11:54:23,352 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/user-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:23,354 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/user-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:23,355 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/vendor-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:23,356 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/vendor-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:23,357 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:23,357 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:23,357 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:23,357 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/consume_data - wb: [644] 25 bytes
2019-07-22 11:54:23,357 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/consume_data'>)
2019-07-22 11:54:23,357 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2019-07-22 11:54:23,358 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2019-07-22 11:54:23,358 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2019-07-22 11:54:23,358 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2019-07-22 11:54:23,358 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2019-07-22 11:54:23,358 - stages.py[DEBUG]: Added default handler for {'text/upstart-job'} from UpstartJobPartHandler: [['text/upstart-job']]
2019-07-22 11:54:23,358 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,358 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,358 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2019-07-22 11:54:23,358 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2019-07-22 11:54:23,359 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/cloud-config.txt - wb: [600] 0 bytes
2019-07-22 11:54:23,359 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:23,359 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2019-07-22 11:54:23,360 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2019-07-22 11:54:23,360 - stages.py[DEBUG]: no vendordata from datasource
2019-07-22 11:54:23,360 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2019-07-22 11:54:23,360 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:23,360 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:23,360 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,370 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:23,370 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:23,370 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,372 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:23,372 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:23,372 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,375 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:23,375 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:23,375 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,376 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,376 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:23,376 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:23,376 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:23,376 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,376 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:23,377 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:23,377 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:23,377 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:23,377 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:23,378 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2019-07-22 11:54:23,379 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8537 bytes
2019-07-22 11:54:23,379 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2019-07-22 11:54:23,380 - main.py[DEBUG]: used datasource 'DataSourceEc2Local' from 'Ec2' was in di_report's list: ['Ec2', 'None']
2019-07-22 11:54:23,443 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:23,444 - stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2019-07-22 11:54:23,444 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2019-07-22 11:54:23,444 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f8742ca3828>)
2019-07-22 11:54:23,444 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2019-07-22 11:54:23,445 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2019-07-22 11:54:23,445 - stages.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2019-07-22 11:54:23,445 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2019-07-22 11:54:23,445 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_seed_random - wb: [644] 25 bytes
2019-07-22 11:54:23,445 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_seed_random'>)
2019-07-22 11:54:23,445 - cc_seed_random.py[DEBUG]: no command provided
2019-07-22 11:54:23,446 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2019-07-22 11:54:23,446 - stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2019-07-22 11:54:23,446 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2019-07-22 11:54:23,446 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f8742ca6048>)
2019-07-22 11:54:23,446 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2019-07-22 11:54:23,446 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2019-07-22 11:54:23,446 - stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2019-07-22 11:54:23,446 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2019-07-22 11:54:23,446 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_write_files - wb: [644] 25 bytes
2019-07-22 11:54:23,447 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_write_files'>)
2019-07-22 11:54:23,447 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2019-07-22 11:54:23,447 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2019-07-22 11:54:23,447 - stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2019-07-22 11:54:23,447 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2019-07-22 11:54:23,447 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f8742ca64a8>)
2019-07-22 11:54:23,447 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'devices': ['/'], 'mode': 'auto', 'ignore_growroot_disabled': False}
2019-07-22 11:54:23,447 - util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,452 - util.py[DEBUG]: Reading from /proc/1327/mountinfo (quiet=False)
2019-07-22 11:54:23,453 - util.py[DEBUG]: Read 2627 bytes from /proc/1327/mountinfo
2019-07-22 11:54:23,453 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,454 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,456 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,458 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:23,458 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:23,458 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:23,458 - util.py[DEBUG]: Read 972 bytes from /proc/self/status
2019-07-22 11:54:23,461 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:23,461 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:23,461 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2019-07-22 11:54:23,461 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2019-07-22 11:54:23,461 - util.py[DEBUG]: Reading from /sys/devices/vbd-768/block/xvda/dev (quiet=False)
2019-07-22 11:54:23,462 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-768/block/xvda/dev
2019-07-22 11:54:23,462 - util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,509 - util.py[DEBUG]: Running command ['growpart', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,553 - util.py[DEBUG]: resize_devices took 0.100 seconds
2019-07-22 11:54:23,553 - cc_growpart.py[INFO]: '/' resized: changed (/dev/xvda, 1) from 8588869120 to 32211189248
2019-07-22 11:54:23,553 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2019-07-22 11:54:23,553 - stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2019-07-22 11:54:23,553 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2019-07-22 11:54:23,553 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f8742c9d128>)
2019-07-22 11:54:23,554 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present
2019-07-22 11:54:23,554 - util.py[DEBUG]: Reading from /proc/1327/mountinfo (quiet=False)
2019-07-22 11:54:23,554 - util.py[DEBUG]: Read 2627 bytes from /proc/1327/mountinfo
2019-07-22 11:54:23,554 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2019-07-22 11:54:23,554 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,556 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,557 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,558 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:23,559 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:23,559 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:23,559 - util.py[DEBUG]: Read 973 bytes from /proc/self/status
2019-07-22 11:54:23,559 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
2019-07-22 11:54:23,559 - util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,586 - util.py[DEBUG]: Resizing took 0.027 seconds
2019-07-22 11:54:23,586 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2019-07-22 11:54:23,586 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2019-07-22 11:54:23,587 - stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2019-07-22 11:54:23,587 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2019-07-22 11:54:23,587 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_disk_setup - wb: [644] 25 bytes
2019-07-22 11:54:23,587 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_disk_setup'>)
2019-07-22 11:54:23,588 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2019-07-22 11:54:23,588 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2019-07-22 11:54:23,588 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2019-07-22 11:54:23,588 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_mounts - wb: [644] 25 bytes
2019-07-22 11:54:23,588 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_mounts'>)
2019-07-22 11:54:23,588 - cc_mounts.py[DEBUG]: mounts configuration is []
2019-07-22 11:54:23,589 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2019-07-22 11:54:23,589 - util.py[DEBUG]: Read 51 bytes from /etc/fstab
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2019-07-22 11:54:23,589 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: changed default device swap => None
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: no need to setup swap
2019-07-22 11:54:23,589 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2019-07-22 11:54:23,589 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2019-07-22 11:54:23,589 - stages.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2019-07-22 11:54:23,590 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2019-07-22 11:54:23,590 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_set_hostname - wb: [644] 25 bytes
2019-07-22 11:54:23,590 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_set_hostname'>)
2019-07-22 11:54:23,590 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:23,590 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:23,590 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:23,590 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2019-07-22 11:54:23,590 - stages.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2019-07-22 11:54:23,591 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2019-07-22 11:54:23,591 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f8742c9d0b8>)
2019-07-22 11:54:23,591 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-0-233.eu-west-1.compute.internal (ip-10-0-0-233)
2019-07-22 11:54:23,591 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:23,591 - util.py[DEBUG]: Read 14 bytes from /etc/hostname
2019-07-22 11:54:23,591 - __init__.py[DEBUG]: Attempting to update hostname to ip-10-0-0-233 in 1 files
2019-07-22 11:54:23,591 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2019-07-22 11:54:23,591 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 14 bytes
2019-07-22 11:54:23,592 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2019-07-22 11:54:23,592 - stages.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2019-07-22 11:54:23,592 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2019-07-22 11:54:23,592 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f8742ca6470>)
2019-07-22 11:54:23,592 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2019-07-22 11:54:23,592 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2019-07-22 11:54:23,592 - stages.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2019-07-22 11:54:23,592 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2019-07-22 11:54:23,592 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ca_certs - wb: [644] 24 bytes
2019-07-22 11:54:23,593 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ca_certs'>)
2019-07-22 11:54:23,593 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca-certs' key in configuration
2019-07-22 11:54:23,593 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2019-07-22 11:54:23,593 - stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2019-07-22 11:54:23,593 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2019-07-22 11:54:23,593 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_rsyslog - wb: [644] 24 bytes
2019-07-22 11:54:23,594 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_rsyslog'>)
2019-07-22 11:54:23,594 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2019-07-22 11:54:23,594 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2019-07-22 11:54:23,594 - stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2019-07-22 11:54:23,594 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2019-07-22 11:54:23,594 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_users_groups - wb: [644] 24 bytes
2019-07-22 11:54:23,594 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_users_groups'>)
2019-07-22 11:54:23,595 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:23,595 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:23,595 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:23,595 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:23,595 - __init__.py[DEBUG]: Adding user ubuntu
2019-07-22 11:54:23,596 - util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2019-07-22 11:54:23,647 - util.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,659 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2019-07-22 11:54:23,660 - util.py[DEBUG]: Read 755 bytes from /etc/sudoers
2019-07-22 11:54:23,661 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 151 bytes
2019-07-22 11:54:23,662 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2019-07-22 11:54:23,662 - stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2019-07-22 11:54:23,662 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2019-07-22 11:54:23,662 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh - wb: [644] 24 bytes
2019-07-22 11:54:23,662 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh'>)
2019-07-22 11:54:23,663 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,748 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,939 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,942 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:23,947 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2019-07-22 11:54:23,948 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:23,948 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:23,949 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 448 bytes
2019-07-22 11:54:23,950 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2019-07-22 11:54:23,950 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2019-07-22 11:54:23,950 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:23,950 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:23,951 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 603 bytes
2019-07-22 11:54:23,951 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2019-07-22 11:54:23,951 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2019-07-22 11:54:23,952 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:23,952 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:23,952 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:23,952 - util.py[DEBUG]: cloud-init mode 'init' took 0.684 seconds (0.69)
2019-07-22 11:54:23,952 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2019-07-22 11:54:30,991 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:config' at Mon, 22 Jul 2019 11:54:30 +0000. Up 15.45 seconds.
2019-07-22 11:54:31,038 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:31,039 - stages.py[DEBUG]: Running module emit_upstart (<module 'cloudinit.config.cc_emit_upstart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_emit_upstart.py'>) with frequency always
2019-07-22 11:54:31,039 - handlers.py[DEBUG]: start: modules-config/config-emit_upstart: running config-emit_upstart with frequency always
2019-07-22 11:54:31,039 - helpers.py[DEBUG]: Running config-emit_upstart using lock (<cloudinit.helpers.DummyLock object at 0x7f242990e9b0>)
2019-07-22 11:54:31,039 - cc_emit_upstart.py[DEBUG]: no /sbin/initctl located
2019-07-22 11:54:31,039 - cc_emit_upstart.py[DEBUG]: not upstart system, 'emit_upstart' disabled
2019-07-22 11:54:31,039 - handlers.py[DEBUG]: finish: modules-config/config-emit_upstart: SUCCESS: config-emit_upstart ran successfully
2019-07-22 11:54:31,039 - stages.py[DEBUG]: Running module snap (<module 'cloudinit.config.cc_snap' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap.py'>) with frequency once-per-instance
2019-07-22 11:54:31,039 - handlers.py[DEBUG]: start: modules-config/config-snap: running config-snap with frequency once-per-instance
2019-07-22 11:54:31,040 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snap - wb: [644] 25 bytes
2019-07-22 11:54:31,040 - helpers.py[DEBUG]: Running config-snap using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snap'>)
2019-07-22 11:54:31,040 - cc_snap.py[DEBUG]: Skipping module named snap, no 'snap' key in configuration
2019-07-22 11:54:31,040 - handlers.py[DEBUG]: finish: modules-config/config-snap: SUCCESS: config-snap ran successfully
2019-07-22 11:54:31,040 - stages.py[DEBUG]: Running module snap_config (<module 'cloudinit.config.cc_snap_config' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap_config.py'>) with frequency once-per-instance
2019-07-22 11:54:31,040 - handlers.py[DEBUG]: start: modules-config/config-snap_config: running config-snap_config with frequency once-per-instance
2019-07-22 11:54:31,040 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snap_config - wb: [644] 25 bytes
2019-07-22 11:54:31,041 - helpers.py[DEBUG]: Running config-snap_config using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snap_config'>)
2019-07-22 11:54:31,041 - cc_snap_config.py[DEBUG]: No snappy config provided, skipping
2019-07-22 11:54:31,041 - handlers.py[DEBUG]: finish: modules-config/config-snap_config: SUCCESS: config-snap_config ran successfully
2019-07-22 11:54:31,041 - stages.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2019-07-22 11:54:31,041 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2019-07-22 11:54:31,041 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh_import_id - wb: [644] 25 bytes
2019-07-22 11:54:31,042 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh_import_id'>)
2019-07-22 11:54:31,042 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2019-07-22 11:54:31,042 - stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2019-07-22 11:54:31,042 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2019-07-22 11:54:31,042 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_locale - wb: [644] 24 bytes
2019-07-22 11:54:31,043 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_locale'>)
2019-07-22 11:54:31,043 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:31,043 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:31,043 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2019-07-22 11:54:31,043 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:31,043 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:31,043 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2019-07-22 11:54:31,043 - util.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:31,634 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2019-07-22 11:54:31,635 - util.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:31,686 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2019-07-22 11:54:31,686 - stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2019-07-22 11:54:31,686 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2019-07-22 11:54:31,686 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_set_passwords - wb: [644] 25 bytes
2019-07-22 11:54:31,687 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_set_passwords'>)
2019-07-22 11:54:31,687 - cc_set_passwords.py[DEBUG]: Leaving ssh config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2019-07-22 11:54:31,687 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2019-07-22 11:54:31,687 - stages.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2019-07-22 11:54:31,687 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2019-07-22 11:54:31,687 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_grub_dpkg - wb: [644] 23 bytes
2019-07-22 11:54:31,688 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_grub_dpkg'>)
2019-07-22 11:54:31,688 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/xvda','false'
2019-07-22 11:54:31,688 - util.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:31,859 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2019-07-22 11:54:31,859 - stages.py[DEBUG]: Running module apt-pipelining (<module 'cloudinit.config.cc_apt_pipelining' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_pipelining.py'>) with frequency once-per-instance
2019-07-22 11:54:31,860 - handlers.py[DEBUG]: start: modules-config/config-apt-pipelining: running config-apt-pipelining with frequency once-per-instance
2019-07-22 11:54:31,860 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_apt_pipelining - wb: [644] 25 bytes
2019-07-22 11:54:31,860 - helpers.py[DEBUG]: Running config-apt-pipelining using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_apt_pipelining'>)
2019-07-22 11:54:31,860 - util.py[DEBUG]: Writing to /etc/apt/apt.conf.d/90cloud-init-pipelining - wb: [644] 80 bytes
2019-07-22 11:54:31,861 - cc_apt_pipelining.py[DEBUG]: Wrote /etc/apt/apt.conf.d/90cloud-init-pipelining with apt pipeline depth setting 0
2019-07-22 11:54:31,861 - handlers.py[DEBUG]: finish: modules-config/config-apt-pipelining: SUCCESS: config-apt-pipelining ran successfully
2019-07-22 11:54:31,861 - stages.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2019-07-22 11:54:31,861 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2019-07-22 11:54:31,861 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_apt_configure - wb: [644] 25 bytes
2019-07-22 11:54:31,862 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_apt_configure'>)
2019-07-22 11:54:31,862 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2019-07-22 11:54:31,862 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:31,862 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:31,862 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:31,862 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:31,862 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2019-07-22 11:54:31,863 - util.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:31,906 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:31,908 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2019-07-22 11:54:31,908 - cc_apt_configure.py[DEBUG]: got security mirror: None
2019-07-22 11:54:31,908 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:32,035 - util.py[DEBUG]: Resolving URL: http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ took 0.125 seconds
2019-07-22 11:54:32,036 - __init__.py[DEBUG]: filtered distro mirror info: {'security': 'http://security.ubuntu.com/ubuntu', 'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/'}
2019-07-22 11:54:32,036 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'security': 'http://security.ubuntu.com/ubuntu', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'MIRROR': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/'}
2019-07-22 11:54:32,036 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2019-07-22 11:54:32,036 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.tmpl (quiet=False)
2019-07-22 11:54:32,037 - util.py[DEBUG]: Read 2841 bytes from /etc/cloud/templates/sources.list.ubuntu.tmpl
2019-07-22 11:54:32,044 - util.py[DEBUG]: Writing to /etc/apt/sources.list - wb: [644] 3335 bytes
2019-07-22 11:54:32,044 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:32,048 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2019-07-22 11:54:32,048 - stages.py[DEBUG]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) with frequency once-per-instance
2019-07-22 11:54:32,048 - handlers.py[DEBUG]: start: modules-config/config-ubuntu-advantage: running config-ubuntu-advantage with frequency once-per-instance
2019-07-22 11:54:32,048 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ubuntu_advantage - wb: [644] 24 bytes
2019-07-22 11:54:32,049 - helpers.py[DEBUG]: Running config-ubuntu-advantage using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ubuntu_advantage'>)
2019-07-22 11:54:32,049 - cc_ubuntu_advantage.py[DEBUG]: Skipping module named ubuntu-advantage, no 'ubuntu-advantage' key in configuration
2019-07-22 11:54:32,049 - handlers.py[DEBUG]: finish: modules-config/config-ubuntu-advantage: SUCCESS: config-ubuntu-advantage ran successfully
2019-07-22 11:54:32,049 - stages.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2019-07-22 11:54:32,049 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2019-07-22 11:54:32,049 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ntp - wb: [644] 25 bytes
2019-07-22 11:54:32,049 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ntp'>)
2019-07-22 11:54:32,049 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2019-07-22 11:54:32,050 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2019-07-22 11:54:32,050 - stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2019-07-22 11:54:32,050 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2019-07-22 11:54:32,050 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_timezone - wb: [644] 25 bytes
2019-07-22 11:54:32,050 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_timezone'>)
2019-07-22 11:54:32,050 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2019-07-22 11:54:32,050 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2019-07-22 11:54:32,050 - stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2019-07-22 11:54:32,051 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2019-07-22 11:54:32,051 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f242990e860>)
2019-07-22 11:54:32,051 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2019-07-22 11:54:32,051 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2019-07-22 11:54:32,051 - stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2019-07-22 11:54:32,051 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2019-07-22 11:54:32,051 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_runcmd - wb: [644] 25 bytes
2019-07-22 11:54:32,052 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_runcmd'>)
2019-07-22 11:54:32,052 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2019-07-22 11:54:32,052 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2019-07-22 11:54:32,052 - stages.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2019-07-22 11:54:32,052 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2019-07-22 11:54:32,052 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_byobu - wb: [644] 25 bytes
2019-07-22 11:54:32,052 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_byobu'>)
2019-07-22 11:54:32,052 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2019-07-22 11:54:32,053 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2019-07-22 11:54:32,053 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:32,053 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:32,053 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:32,053 - util.py[DEBUG]: cloud-init mode 'modules' took 1.108 seconds (1.11)
2019-07-22 11:54:32,054 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2019-07-22 11:54:32,350 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:final' at Mon, 22 Jul 2019 11:54:32 +0000. Up 16.81 seconds.
2019-07-22 11:54:32,397 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:32,398 - stages.py[DEBUG]: Running module snappy (<module 'cloudinit.config.cc_snappy' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snappy.py'>) with frequency once-per-instance
2019-07-22 11:54:32,398 - handlers.py[DEBUG]: start: modules-final/config-snappy: running config-snappy with frequency once-per-instance
2019-07-22 11:54:32,398 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snappy - wb: [644] 25 bytes
2019-07-22 11:54:32,399 - helpers.py[DEBUG]: Running config-snappy using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_snappy'>)
2019-07-22 11:54:32,399 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:32,399 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:32,400 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:32,400 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:32,400 - cc_snappy.py[DEBUG]: snappy: 'auto' mode, and system not snappy
2019-07-22 11:54:32,400 - handlers.py[DEBUG]: finish: modules-final/config-snappy: SUCCESS: config-snappy ran successfully
2019-07-22 11:54:32,400 - stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance
2019-07-22 11:54:32,400 - handlers.py[DEBUG]: start: modules-final/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
2019-07-22 11:54:32,400 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_package_update_upgrade_install - wb: [644] 25 bytes
2019-07-22 11:54:32,401 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_package_update_upgrade_install'>)
2019-07-22 11:54:32,401 - handlers.py[DEBUG]: finish: modules-final/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
2019-07-22 11:54:32,401 - stages.py[DEBUG]: Running module fan (<module 'cloudinit.config.cc_fan' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_fan.py'>) with frequency once-per-instance
2019-07-22 11:54:32,401 - handlers.py[DEBUG]: start: modules-final/config-fan: running config-fan with frequency once-per-instance
2019-07-22 11:54:32,401 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_fan - wb: [644] 25 bytes
2019-07-22 11:54:32,402 - helpers.py[DEBUG]: Running config-fan using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_fan'>)
2019-07-22 11:54:32,402 - cc_fan.py[DEBUG]: fan: no 'fan' config entry. disabling
2019-07-22 11:54:32,402 - handlers.py[DEBUG]: finish: modules-final/config-fan: SUCCESS: config-fan ran successfully
2019-07-22 11:54:32,402 - stages.py[DEBUG]: Running module landscape (<module 'cloudinit.config.cc_landscape' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_landscape.py'>) with frequency once-per-instance
2019-07-22 11:54:32,402 - handlers.py[DEBUG]: start: modules-final/config-landscape: running config-landscape with frequency once-per-instance
2019-07-22 11:54:32,402 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_landscape - wb: [644] 25 bytes
2019-07-22 11:54:32,402 - helpers.py[DEBUG]: Running config-landscape using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_landscape'>)
2019-07-22 11:54:32,403 - handlers.py[DEBUG]: finish: modules-final/config-landscape: SUCCESS: config-landscape ran successfully
2019-07-22 11:54:32,403 - stages.py[DEBUG]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) with frequency once-per-instance
2019-07-22 11:54:32,403 - handlers.py[DEBUG]: start: modules-final/config-lxd: running config-lxd with frequency once-per-instance
2019-07-22 11:54:32,403 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_lxd - wb: [644] 25 bytes
2019-07-22 11:54:32,403 - helpers.py[DEBUG]: Running config-lxd using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_lxd'>)
2019-07-22 11:54:32,403 - cc_lxd.py[DEBUG]: Skipping module named lxd, not present or disabled by cfg
2019-07-22 11:54:32,403 - handlers.py[DEBUG]: finish: modules-final/config-lxd: SUCCESS: config-lxd ran successfully
2019-07-22 11:54:32,403 - stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_puppet.py'>) with frequency once-per-instance
2019-07-22 11:54:32,404 - handlers.py[DEBUG]: start: modules-final/config-puppet: running config-puppet with frequency once-per-instance
2019-07-22 11:54:32,404 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_puppet - wb: [644] 25 bytes
2019-07-22 11:54:32,404 - helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_puppet'>)
2019-07-22 11:54:32,404 - cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
2019-07-22 11:54:32,404 - handlers.py[DEBUG]: finish: modules-final/config-puppet: SUCCESS: config-puppet ran successfully
2019-07-22 11:54:32,404 - stages.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py'>) with frequency once-per-instance
2019-07-22 11:54:32,404 - handlers.py[DEBUG]: start: modules-final/config-chef: running config-chef with frequency once-per-instance
2019-07-22 11:54:32,405 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_chef - wb: [644] 25 bytes
2019-07-22 11:54:32,405 - helpers.py[DEBUG]: Running config-chef using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_chef'>)
2019-07-22 11:54:32,405 - cc_chef.py[DEBUG]: Skipping module named chef, no 'chef' key in configuration
2019-07-22 11:54:32,405 - handlers.py[DEBUG]: finish: modules-final/config-chef: SUCCESS: config-chef ran successfully
2019-07-22 11:54:32,405 - stages.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mcollective.py'>) with frequency once-per-instance
2019-07-22 11:54:32,405 - handlers.py[DEBUG]: start: modules-final/config-mcollective: running config-mcollective with frequency once-per-instance
2019-07-22 11:54:32,406 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_mcollective - wb: [644] 25 bytes
2019-07-22 11:54:32,406 - helpers.py[DEBUG]: Running config-mcollective using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_mcollective'>)
2019-07-22 11:54:32,406 - cc_mcollective.py[DEBUG]: Skipping module named mcollective, no 'mcollective' key in configuration
2019-07-22 11:54:32,406 - handlers.py[DEBUG]: finish: modules-final/config-mcollective: SUCCESS: config-mcollective ran successfully
2019-07-22 11:54:32,406 - stages.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_salt_minion.py'>) with frequency once-per-instance
2019-07-22 11:54:32,406 - handlers.py[DEBUG]: start: modules-final/config-salt-minion: running config-salt-minion with frequency once-per-instance
2019-07-22 11:54:32,406 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_salt_minion - wb: [644] 25 bytes
2019-07-22 11:54:32,407 - helpers.py[DEBUG]: Running config-salt-minion using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_salt_minion'>)
2019-07-22 11:54:32,407 - cc_salt_minion.py[DEBUG]: Skipping module named salt-minion, no 'salt_minion' key in configuration
2019-07-22 11:54:32,407 - handlers.py[DEBUG]: finish: modules-final/config-salt-minion: SUCCESS: config-salt-minion ran successfully
2019-07-22 11:54:32,407 - stages.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2019-07-22 11:54:32,407 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2019-07-22 11:54:32,407 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_rightscale_userdata - wb: [644] 25 bytes
2019-07-22 11:54:32,408 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_rightscale_userdata'>)
2019-07-22 11:54:32,408 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2019-07-22 11:54:32,408 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2019-07-22 11:54:32,408 - stages.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2019-07-22 11:54:32,408 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2019-07-22 11:54:32,408 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_vendor - wb: [644] 25 bytes
2019-07-22 11:54:32,408 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_vendor'>)
2019-07-22 11:54:32,409 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2019-07-22 11:54:32,409 - stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2019-07-22 11:54:32,409 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2019-07-22 11:54:32,409 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 24 bytes
2019-07-22 11:54:32,409 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2019-07-22 11:54:32,409 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2019-07-22 11:54:32,410 - stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2019-07-22 11:54:32,410 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2019-07-22 11:54:32,410 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7fd4c8229358>)
2019-07-22 11:54:32,410 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2019-07-22 11:54:32,410 - stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2019-07-22 11:54:32,410 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2019-07-22 11:54:32,410 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_per_instance - wb: [644] 24 bytes
2019-07-22 11:54:32,411 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_per_instance'>)
2019-07-22 11:54:32,411 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2019-07-22 11:54:32,411 - stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2019-07-22 11:54:32,411 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2019-07-22 11:54:32,411 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_user - wb: [644] 25 bytes
2019-07-22 11:54:32,412 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_scripts_user'>)
2019-07-22 11:54:32,412 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2019-07-22 11:54:32,412 - stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2019-07-22 11:54:32,412 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2019-07-22 11:54:32,412 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2019-07-22 11:54:32,412 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_ssh_authkey_fingerprints'>)
2019-07-22 11:54:32,413 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:32,413 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:32,413 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2019-07-22 11:54:32,413 - util.py[DEBUG]: Read 448 bytes from /home/ubuntu/.ssh/authorized_keys
2019-07-22 11:54:32,441 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2019-07-22 11:54:32,441 - stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2019-07-22 11:54:32,441 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2019-07-22 11:54:32,442 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_keys_to_console - wb: [644] 25 bytes
2019-07-22 11:54:32,442 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_keys_to_console'>)
2019-07-22 11:54:32,442 - util.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:32,456 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2019-07-22 11:54:32,456 - stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2019-07-22 11:54:32,457 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2019-07-22 11:54:32,457 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_phone_home - wb: [644] 25 bytes
2019-07-22 11:54:32,457 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_phone_home'>)
2019-07-22 11:54:32,457 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2019-07-22 11:54:32,457 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2019-07-22 11:54:32,457 - stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2019-07-22 11:54:32,458 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2019-07-22 11:54:32,458 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fd4c7a97198>)
2019-07-22 11:54:32,458 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:32,458 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:32,461 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 finished at Mon, 22 Jul 2019 11:54:32 +0000. Datasource DataSourceEc2Local.  Up 16.96 seconds
2019-07-22 11:54:32,461 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 79 bytes
2019-07-22 11:54:32,461 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2019-07-22 11:54:32,461 - stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2019-07-22 11:54:32,461 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2019-07-22 11:54:32,461 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_power_state_change - wb: [644] 24 bytes
2019-07-22 11:54:32,462 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-05b3c198c7419b4f8/sem/config_power_state_change'>)
2019-07-22 11:54:32,462 - cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
2019-07-22 11:54:32,462 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2019-07-22 11:54:32,462 - main.py[DEBUG]: Ran 20 modules with 0 failures
2019-07-22 11:54:32,463 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2019-07-22 11:54:32,463 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:32,463 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:32,463 - util.py[DEBUG]: cloud-init mode 'modules' took 0.160 seconds (0.16)
2019-07-22 11:54:32,463 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
