2019-07-22 11:54:24,212 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init-local' at Mon, 22 Jul 2019 11:54:24 +0000. Up 5.50 seconds.
2019-07-22 11:54:24,212 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:24,212 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:24,215 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:24,216 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:24,216 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2019-07-22 11:54:24,216 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
2019-07-22 11:54:24,216 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2019-07-22 11:54:24,217 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:24,217 - stages.py[DEBUG]: no cache found
2019-07-22 11:54:24,217 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2019-07-22 11:54:24,217 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:24,219 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:24,219 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2019-07-22 11:54:24,247 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:24,248 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:24,270 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceOpenStackLocal', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceEc2Local']
2019-07-22 11:54:24,270 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2019-07-22 11:54:24,270 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2019-07-22 11:54:24,271 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,271 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,273 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,274 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,275 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,275 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,275 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,276 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:24,276 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec268e32-3145-f428-e1fd-845b2e6748fd
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2019-07-22 11:54:24,276 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,278 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,279 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,292 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,304 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,316 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: no local data found from DataSourceNoCloud
2019-07-22 11:54:24,316 - handlers.py[DEBUG]: start: init-local/search-ConfigDrive: searching for local data from DataSourceConfigDrive
2019-07-22 11:54:24,316 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceConfigDrive.DataSourceConfigDrive'>
2019-07-22 11:54:24,316 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,316 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,317 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,319 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd0'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,320 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd1'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,322 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,333 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,345 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=config-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,357 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONFIG-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,369 - DataSourceConfigDrive.py[DEBUG]: devices=[] dslist=['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None']
2019-07-22 11:54:24,369 - handlers.py[DEBUG]: finish: init-local/search-ConfigDrive: SUCCESS: no local data found from DataSourceConfigDrive
2019-07-22 11:54:24,369 - handlers.py[DEBUG]: start: init-local/search-OpenNebula: searching for local data from DataSourceOpenNebula
2019-07-22 11:54:24,369 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenNebula.DataSourceOpenNebula'>
2019-07-22 11:54:24,369 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,369 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONTEXT', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,383 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CDROM', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,395 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,407 - handlers.py[DEBUG]: finish: init-local/search-OpenNebula: SUCCESS: no local data found from DataSourceOpenNebula
2019-07-22 11:54:24,407 - handlers.py[DEBUG]: start: init-local/search-DigitalOcean: searching for local data from DataSourceDigitalOcean
2019-07-22 11:54:24,407 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceDigitalOcean.DataSourceDigitalOcean'>
2019-07-22 11:54:24,408 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,408 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,409 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,411 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,412 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,412 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,412 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,412 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,412 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:24,412 - util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
2019-07-22 11:54:24,412 - util.py[DEBUG]: Read 4 bytes from /sys/class/dmi/id/sys_vendor
2019-07-22 11:54:24,412 - util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Xen
2019-07-22 11:54:24,413 - handlers.py[DEBUG]: finish: init-local/search-DigitalOcean: SUCCESS: no local data found from DataSourceDigitalOcean
2019-07-22 11:54:24,413 - handlers.py[DEBUG]: start: init-local/search-Azure: searching for local data from DataSourceAzure
2019-07-22 11:54:24,413 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'>
2019-07-22 11:54:24,413 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,413 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,415 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,416 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,417 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,417 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,417 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,417 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,417 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:24,417 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:24,417 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:24,417 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:24,418 - DataSourceAzure.py[DEBUG]: Non-Azure DMI asset tag '' discovered.
2019-07-22 11:54:24,418 - handlers.py[DEBUG]: finish: init-local/search-Azure: SUCCESS: no local data found from DataSourceAzure
2019-07-22 11:54:24,418 - handlers.py[DEBUG]: start: init-local/search-OVF: searching for local data from DataSourceOVF
2019-07-22 11:54:24,418 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'>
2019-07-22 11:54:24,418 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,418 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,420 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,421 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,422 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,422 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,422 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,423 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,423 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:24,423 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:24,423 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:24,423 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:24,423 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2019-07-22 11:54:24,423 - util.py[DEBUG]: Read 1991 bytes from /proc/mounts
2019-07-22 11:54:24,423 - util.py[DEBUG]: Fetched {'securityfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/kernel/security', 'fstype': 'securityfs'}, '/dev/xvda1': {'opts': 'rw,relatime,discard,data=ordered', 'mountpoint': '/', 'fstype': 'ext4'}, 'sysfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys', 'fstype': 'sysfs'}, 'debugfs': {'opts': 'rw,relatime', 'mountpoint': '/sys/kernel/debug', 'fstype': 'debugfs'}, 'cgroup': {'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'mountpoint': '/sys/fs/cgroup/blkio', 'fstype': 'cgroup'}, 'devpts': {'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'mountpoint': '/dev/pts', 'fstype': 'devpts'}, 'systemd-1': {'opts': 'rw,relatime,fd=23,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'fstype': 'autofs'}, 'udev': {'opts': 'rw,nosuid,relatime,size=30907648k,nr_inodes=7726912,mode=755', 'mountpoint': '/dev', 'fstype': 'devtmpfs'}, 'pstore': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/fs/pstore', 'fstype': 'pstore'}, 'proc': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/proc', 'fstype': 'proc'}, 'fusectl': {'opts': 'rw,relatime', 'mountpoint': '/sys/fs/fuse/connections', 'fstype': 'fusectl'}, 'mqueue': {'opts': 'rw,relatime', 'mountpoint': '/dev/mqueue', 'fstype': 'mqueue'}, 'tmpfs': {'opts': 'ro,nosuid,nodev,noexec,mode=755', 'mountpoint': '/sys/fs/cgroup', 'fstype': 'tmpfs'}, 'hugetlbfs': {'opts': 'rw,relatime', 'mountpoint': '/dev/hugepages', 'fstype': 'hugetlbfs'}} mounts from proc
2019-07-22 11:54:24,423 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2019-07-22 11:54:24,435 - handlers.py[DEBUG]: finish: init-local/search-OVF: SUCCESS: no local data found from DataSourceOVF
2019-07-22 11:54:24,436 - handlers.py[DEBUG]: start: init-local/search-OpenStackLocal: searching for local data from DataSourceOpenStackLocal
2019-07-22 11:54:24,436 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenStack.DataSourceOpenStackLocal'>
2019-07-22 11:54:24,436 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,436 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,437 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,439 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,440 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,440 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,440 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,440 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,440 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:24,440 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:24,440 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:24,440 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:24,440 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,442 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,443 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,444 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,444 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,445 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,445 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,445 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:24,445 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2019-07-22 11:54:24,445 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2019-07-22 11:54:24,445 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2019-07-22 11:54:24,445 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,445 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,445 - handlers.py[DEBUG]: finish: init-local/search-OpenStackLocal: SUCCESS: no local data found from DataSourceOpenStackLocal
2019-07-22 11:54:24,445 - handlers.py[DEBUG]: start: init-local/search-CloudSigma: searching for local data from DataSourceCloudSigma
2019-07-22 11:54:24,445 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceCloudSigma.DataSourceCloudSigma'>
2019-07-22 11:54:24,445 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,445 - DataSourceCloudSigma.py[DEBUG]: determining hypervisor product name via dmi data
2019-07-22 11:54:24,446 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,447 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,448 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,449 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,449 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,450 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,450 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,450 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:24,450 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:24,450 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:24,450 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:24,450 - DataSourceCloudSigma.py[DEBUG]: detected hypervisor as HVM domU
2019-07-22 11:54:24,450 - handlers.py[DEBUG]: finish: init-local/search-CloudSigma: SUCCESS: no local data found from DataSourceCloudSigma
2019-07-22 11:54:24,450 - handlers.py[DEBUG]: start: init-local/search-SmartOS: searching for local data from DataSourceSmartOS
2019-07-22 11:54:24,450 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceSmartOS.DataSourceSmartOS'>
2019-07-22 11:54:24,451 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,452 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,453 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,454 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,454 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,455 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,455 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,455 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2019-07-22 11:54:24,455 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2019-07-22 11:54:24,455 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2019-07-22 11:54:24,455 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2019-07-22 11:54:24,455 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,455 - DataSourceSmartOS.py[DEBUG]: Not running on smartos
2019-07-22 11:54:24,455 - handlers.py[DEBUG]: finish: init-local/search-SmartOS: SUCCESS: no local data found from DataSourceSmartOS
2019-07-22 11:54:24,455 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2019-07-22 11:54:24,455 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2019-07-22 11:54:24,455 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2019-07-22 11:54:24,456 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2019-07-22 11:54:24,456 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2019-07-22 11:54:24,456 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,457 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,458 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,459 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:24,460 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:24,460 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:24,460 - util.py[DEBUG]: Read 967 bytes from /proc/self/status
2019-07-22 11:54:24,460 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2019-07-22 11:54:24,460 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2019-07-22 11:54:24,460 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2019-07-22 11:54:24,460 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec268e32-3145-f428-e1fd-845b2e6748fd
2019-07-22 11:54:24,460 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_platform=AWS
2019-07-22 11:54:24,460 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:24,460 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:24,461 - util.py[DEBUG]: Reading from /sys/class/net/ens3/name_assign_type (quiet=False)
2019-07-22 11:54:24,461 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/name_assign_type
2019-07-22 11:54:24,461 - util.py[DEBUG]: Reading from /sys/class/net/ens3/carrier (quiet=False)
2019-07-22 11:54:24,461 - util.py[DEBUG]: Reading from /sys/class/net/ens3/dormant (quiet=False)
2019-07-22 11:54:24,461 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:24,461 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:24,461 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:24,461 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:24,462 - dhcp.py[DEBUG]: Performing a dhcp discovery on ens3
2019-07-22 11:54:24,462 - util.py[DEBUG]: Copying /sbin/dhclient to /var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient
2019-07-22 11:54:24,464 - util.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,482 - util.py[DEBUG]: Running command ['/var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient.pid', 'ens3', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,634 - util.py[DEBUG]: All files appeared after 0 seconds: ['/var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient.pid', '/var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhcp.leases']
2019-07-22 11:54:24,634 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient.pid (quiet=False)
2019-07-22 11:54:24,634 - util.py[DEBUG]: Read 5 bytes from /var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhclient.pid
2019-07-22 11:54:24,634 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhcp.leases (quiet=False)
2019-07-22 11:54:24,634 - util.py[DEBUG]: Read 513 bytes from /var/tmp/cloud-init/cloud-init-dhcp-3ex94att/dhcp.leases
2019-07-22 11:54:24,635 - dhcp.py[DEBUG]: Received dhcp lease on ens3 for 10.0.0.194/255.255.255.0
2019-07-22 11:54:24,635 - __init__.py[DEBUG]: Attempting setup of ephemeral network on ens3 with 10.0.0.194/24 brd 10.0.0.255
2019-07-22 11:54:24,635 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '10.0.0.194/24', 'broadcast', '10.0.0.255', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,637 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'up'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,640 - util.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,642 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', 'default', 'via', '10.0.0.1', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,647 - util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.003 seconds
2019-07-22 11:54:24,647 - util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.000 seconds
2019-07-22 11:54:24,647 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2019-07-22 11:54:24,648 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2009-04-04/meta-data/instance-id' with {'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2009-04-04/meta-data/instance-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,653 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2009-04-04/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:24,653 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2019-07-22 11:54:24,653 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,655 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:24,655 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
2019-07-22 11:54:24,655 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/user-data', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,657 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,658 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 268b) after 1 attempts
2019-07-22 11:54:24,658 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,660 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 30b) after 1 attempts
2019-07-22 11:54:24,660 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,661 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2019-07-22 11:54:24,662 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,663 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral1 (200, 3b) after 1 attempts
2019-07-22 11:54:24,663 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,665 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ephemeral0 (200, 3b) after 1 attempts
2019-07-22 11:54:24,665 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,666 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
2019-07-22 11:54:24,667 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,668 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/ (200, 26b) after 1 attempts
2019-07-22 11:54:24,668 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/info' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/info', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,670 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/info (200, 245b) after 1 attempts
2019-07-22 11:54:24,670 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,671 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
2019-07-22 11:54:24,671 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,673 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2019-07-22 11:54:24,673 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,674 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
2019-07-22 11:54:24,675 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,676 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2019-07-22 11:54:24,676 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,678 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2019-07-22 11:54:24,678 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,679 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ (200, 230b) after 1 attempts
2019-07-22 11:54:24,680 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,681 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/ (200, 13b) after 1 attempts
2019-07-22 11:54:24,681 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/52.209.80.219' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/52.209.80.219', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/ipv4-associations/52.209.80.219 (200, 10b) after 1 attempts
2019-07-22 11:54:24,683 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,684 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-id (200, 24b) after 1 attempts
2019-07-22 11:54:24,684 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-block' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-block', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,686 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:24,686 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/interface-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/interface-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,688 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/interface-id (200, 21b) after 1 attempts
2019-07-22 11:54:24,688 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-group-ids' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-group-ids', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,690 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-group-ids (200, 20b) after 1 attempts
2019-07-22 11:54:24,690 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/owner-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/owner-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,692 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/owner-id (200, 12b) after 1 attempts
2019-07-22 11:54:24,692 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-ipv4-cidr-block' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-ipv4-cidr-block', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,693 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
2019-07-22 11:54:24,693 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/device-number' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/device-number', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,695 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/device-number (200, 1b) after 1 attempts
2019-07-22 11:54:24,695 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,697 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-id (200, 21b) after 1 attempts
2019-07-22 11:54:24,698 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-hostname' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-hostname', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,699 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-hostname (200, 49b) after 1 attempts
2019-07-22 11:54:24,699 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/mac' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/mac', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,701 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/mac (200, 17b) after 1 attempts
2019-07-22 11:54:24,701 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-hostname' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-hostname', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,702 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:24,703 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-ipv4s' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-ipv4s', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,704 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/local-ipv4s (200, 10b) after 1 attempts
2019-07-22 11:54:24,704 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-blocks' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-blocks', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,706 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
2019-07-22 11:54:24,706 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-ipv4s' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-ipv4s', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,707 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/public-ipv4s (200, 13b) after 1 attempts
2019-07-22 11:54:24,707 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-groups' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-groups', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,709 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:3f:db:a2:b2:3a/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:24,709 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,710 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
2019-07-22 11:54:24,711 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,712 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2019-07-22 11:54:24,712 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,714 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 68b) after 1 attempts
2019-07-22 11:54:24,714 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,715 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 448b) after 1 attempts
2019-07-22 11:54:24,716 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,717 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
2019-07-22 11:54:24,717 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,719 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
2019-07-22 11:54:24,719 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,720 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
2019-07-22 11:54:24,720 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,722 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
2019-07-22 11:54:24,722 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,724 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2019-07-22 11:54:24,724 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,725 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
2019-07-22 11:54:24,725 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,727 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
2019-07-22 11:54:24,727 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,728 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 13b) after 1 attempts
2019-07-22 11:54:24,729 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,730 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 10b) after 1 attempts
2019-07-22 11:54:24,730 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,732 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 40b) after 1 attempts
2019-07-22 11:54:24,732 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,733 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 49b) after 1 attempts
2019-07-22 11:54:24,733 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,735 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 40b) after 1 attempts
2019-07-22 11:54:24,735 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,737 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
2019-07-22 11:54:24,737 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,738 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2019-07-22 11:54:24,738 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,740 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 80b) after 1 attempts
2019-07-22 11:54:24,740 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,741 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 10b) after 1 attempts
2019-07-22 11:54:24,742 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,743 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
2019-07-22 11:54:24,743 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,745 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
2019-07-22 11:54:24,745 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,747 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
2019-07-22 11:54:24,748 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,749 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2019-07-22 11:54:24,749 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,751 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
2019-07-22 11:54:24,751 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,753 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
2019-07-22 11:54:24,753 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'timeout': 5.0, 'headers': {'User-Agent': 'Cloud-Init/18.3-9-g2e62cb8a-0ubuntu1~16.04.2'}, 'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'method': 'GET', 'allow_redirects': True} configuration
2019-07-22 11:54:24,757 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
2019-07-22 11:54:24,757 - util.py[DEBUG]: Crawl of metadata service took 0.113 seconds
2019-07-22 11:54:24,757 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', 'default', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,759 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens3', 'down'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,794 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '10.0.0.194/24', 'dev', 'ens3'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,797 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2019-07-22 11:54:24,797 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2019-07-22 11:54:24,798 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:24,798 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:24,798 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,808 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:24,809 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:24,809 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,810 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:24,810 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:24,810 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,813 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:24,813 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:24,814 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,814 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,814 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:24,815 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:24,815 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0801077bcefacb3ae'
2019-07-22 11:54:24,816 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0801077bcefacb3ae/datasource (quiet=False)
2019-07-22 11:54:24,816 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/datasource - wb: [644] 39 bytes
2019-07-22 11:54:24,816 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:24,817 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:24,817 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2019-07-22 11:54:24,817 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:24,817 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:24,817 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2019-07-22 11:54:24,818 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9128 bytes
2019-07-22 11:54:24,818 - main.py[DEBUG]: [local] init will now be targeting instance id: i-0801077bcefacb3ae. new=True
2019-07-22 11:54:24,819 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:24,819 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:24,819 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,829 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:24,829 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:24,829 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,830 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:24,830 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:24,831 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,834 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:24,834 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:24,834 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,834 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:24,835 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:24,835 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:24,836 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-0-194.eu-west-1.compute.internal (ip-10-0-0-194)
2019-07-22 11:54:24,836 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:24,836 - util.py[DEBUG]: Read 7 bytes from /etc/hostname
2019-07-22 11:54:24,836 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 14 bytes
2019-07-22 11:54:24,837 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-10-0-0-194
2019-07-22 11:54:24,837 - util.py[DEBUG]: Running command ['hostname', 'ip-10-0-0-194'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,840 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:24,840 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:24,840 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'name': 'ens3', 'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'mac_address': '06:3f:db:a2:b2:3a'}]}
2019-07-22 11:54:24,840 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:24,840 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:24,840 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:24,840 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:24,840 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:24,840 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:24,841 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:24,841 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:24,842 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,844 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:24,846 - __init__.py[DEBUG]: no work necessary for renaming of [['06:3f:db:a2:b2:3a', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:24,846 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 1, 'config': [{'name': 'ens3', 'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'mac_address': '06:3f:db:a2:b2:3a'}]}
2019-07-22 11:54:24,847 - __init__.py[DEBUG]: Selected renderer 'eni' from priority list: None
2019-07-22 11:54:24,849 - util.py[DEBUG]: Writing to /etc/network/interfaces.d/50-cloud-init.cfg - wb: [644] 367 bytes
2019-07-22 11:54:24,849 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 96 bytes
2019-07-22 11:54:24,850 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2019-07-22 11:54:24,850 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:24,850 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:24,850 - util.py[DEBUG]: cloud-init mode 'init' took 0.666 seconds (0.67)
2019-07-22 11:54:24,851 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2019-07-22 11:54:25,486 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'init' at Mon, 22 Jul 2019 11:54:25 +0000. Up 6.77 seconds.
2019-07-22 11:54:25,486 - main.py[DEBUG]: No kernel command line url found.
2019-07-22 11:54:25,486 - main.py[DEBUG]: Closing stdin.
2019-07-22 11:54:25,487 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2019-07-22 11:54:25,488 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2019-07-22 11:54:25,488 - util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,491 - util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,492 - util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2019-07-22 11:54:25,495 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
2019-07-22 11:54:25,495 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
2019-07-22 11:54:25,495 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2019-07-22 11:54:25,495 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2019-07-22 11:54:25,495 - util.py[DEBUG]: Read 9128 bytes from /var/lib/cloud/instance/obj.pkl
2019-07-22 11:54:25,497 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2019-07-22 11:54:25,497 - util.py[DEBUG]: Read 20 bytes from /run/cloud-init/.instance-id
2019-07-22 11:54:25,498 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:25,498 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2019-07-22 11:54:25,498 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:25,498 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:25,498 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,509 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:25,509 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:25,509 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,510 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:25,510 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:25,510 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,513 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:25,513 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:25,513 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,514 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,514 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:25,514 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2019-07-22 11:54:25,515 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0801077bcefacb3ae'
2019-07-22 11:54:25,515 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0801077bcefacb3ae/datasource (quiet=False)
2019-07-22 11:54:25,515 - util.py[DEBUG]: Read 39 bytes from /var/lib/cloud/instances/i-0801077bcefacb3ae/datasource
2019-07-22 11:54:25,515 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/datasource - wb: [644] 39 bytes
2019-07-22 11:54:25,516 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2019-07-22 11:54:25,516 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2019-07-22 11:54:25,516 - util.py[DEBUG]: Read 20 bytes from /var/lib/cloud/data/instance-id
2019-07-22 11:54:25,516 - stages.py[DEBUG]: previous iid found to be i-0801077bcefacb3ae
2019-07-22 11:54:25,516 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2019-07-22 11:54:25,516 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2019-07-22 11:54:25,517 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2019-07-22 11:54:25,517 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9204 bytes
2019-07-22 11:54:25,518 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0801077bcefacb3ae. new=False
2019-07-22 11:54:25,518 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:25,518 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:25,518 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,528 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:25,528 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:25,528 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,529 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:25,529 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:25,529 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,532 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:25,532 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:25,532 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,533 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,533 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:25,534 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:25,534 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:25,534 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'subnets': [{'type': 'dhcp4'}], 'type': 'physical', 'name': 'ens3', 'mac_address': '06:3f:db:a2:b2:3a'}]}
2019-07-22 11:54:25,535 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:25,535 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:25,535 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:25,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2019-07-22 11:54:25,535 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2019-07-22 11:54:25,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2019-07-22 11:54:25,535 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2019-07-22 11:54:25,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2019-07-22 11:54:25,535 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2019-07-22 11:54:25,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/ens3/addr_assign_type (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens3/addr_assign_type
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/ens3/uevent (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens3/uevent
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/ens3/address (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens3/address
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/ens3/device/device (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens3/device/device
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2019-07-22 11:54:25,536 - util.py[DEBUG]: Reading from /sys/class/net/ens3/operstate (quiet=False)
2019-07-22 11:54:25,536 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/ens3/operstate
2019-07-22 11:54:25,536 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,538 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,540 - __init__.py[DEBUG]: no work necessary for renaming of [['06:3f:db:a2:b2:3a', 'ens3', 'ixgbevf', '0x10ed']]
2019-07-22 11:54:25,540 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
2019-07-22 11:54:25,540 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2019-07-22 11:54:25,540 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2019-07-22 11:54:25,540 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/user-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:25,543 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/user-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:25,543 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/vendor-data.txt - wb: [600] 0 bytes
2019-07-22 11:54:25,544 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/vendor-data.txt.i - wb: [600] 308 bytes
2019-07-22 11:54:25,545 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:25,546 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:25,546 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:25,546 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/consume_data - wb: [644] 25 bytes
2019-07-22 11:54:25,546 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/consume_data'>)
2019-07-22 11:54:25,547 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2019-07-22 11:54:25,547 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2019-07-22 11:54:25,547 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']]
2019-07-22 11:54:25,547 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2019-07-22 11:54:25,547 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2019-07-22 11:54:25,547 - stages.py[DEBUG]: Added default handler for {'text/upstart-job'} from UpstartJobPartHandler: [['text/upstart-job']]
2019-07-22 11:54:25,547 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,547 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,547 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']] (__begin__, None, 3) with frequency once-per-instance
2019-07-22 11:54:25,547 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'MIME-Version': '1.0', 'Content-Disposition': 'attachment; filename="part-001"'}
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config-jsonp', 'text/cloud-config']] (__end__, None, 3) with frequency once-per-instance
2019-07-22 11:54:25,548 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/cloud-config.txt - wb: [600] 0 bytes
2019-07-22 11:54:25,548 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2019-07-22 11:54:25,548 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2019-07-22 11:54:25,549 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2019-07-22 11:54:25,549 - stages.py[DEBUG]: no vendordata from datasource
2019-07-22 11:54:25,549 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2019-07-22 11:54:25,549 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2019-07-22 11:54:25,549 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
2019-07-22 11:54:25,549 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,559 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2019-07-22 11:54:25,559 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2019-07-22 11:54:25,559 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,561 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2019-07-22 11:54:25,561 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2019-07-22 11:54:25,561 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,564 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2019-07-22 11:54:25,564 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2019-07-22 11:54:25,564 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,564 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,565 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:25,565 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:25,565 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:25,565 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,565 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:25,566 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2019-07-22 11:54:25,566 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2019-07-22 11:54:25,566 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2019-07-22 11:54:25,566 - util.py[DEBUG]: loaded blob returned None, returning default.
2019-07-22 11:54:25,567 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2019-07-22 11:54:25,568 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8526 bytes
2019-07-22 11:54:25,568 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2019-07-22 11:54:25,569 - main.py[DEBUG]: used datasource 'DataSourceEc2Local' from 'Ec2' was in di_report's list: ['Ec2', 'None']
2019-07-22 11:54:25,622 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:25,623 - stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2019-07-22 11:54:25,623 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2019-07-22 11:54:25,623 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea5881f98>)
2019-07-22 11:54:25,623 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2019-07-22 11:54:25,624 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2019-07-22 11:54:25,624 - stages.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2019-07-22 11:54:25,624 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2019-07-22 11:54:25,624 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_seed_random - wb: [644] 25 bytes
2019-07-22 11:54:25,624 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_seed_random'>)
2019-07-22 11:54:25,624 - cc_seed_random.py[DEBUG]: no command provided
2019-07-22 11:54:25,624 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2019-07-22 11:54:25,625 - stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2019-07-22 11:54:25,625 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2019-07-22 11:54:25,625 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea58869b0>)
2019-07-22 11:54:25,625 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2019-07-22 11:54:25,625 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2019-07-22 11:54:25,625 - stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2019-07-22 11:54:25,625 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2019-07-22 11:54:25,625 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_write_files - wb: [644] 25 bytes
2019-07-22 11:54:25,626 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_write_files'>)
2019-07-22 11:54:25,626 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2019-07-22 11:54:25,626 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2019-07-22 11:54:25,626 - stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2019-07-22 11:54:25,626 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2019-07-22 11:54:25,626 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea5886f28>)
2019-07-22 11:54:25,626 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'devices': ['/'], 'ignore_growroot_disabled': False, 'mode': 'auto'}
2019-07-22 11:54:25,626 - util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,630 - util.py[DEBUG]: Reading from /proc/1325/mountinfo (quiet=False)
2019-07-22 11:54:25,630 - util.py[DEBUG]: Read 2627 bytes from /proc/1325/mountinfo
2019-07-22 11:54:25,630 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,632 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,634 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,635 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:25,635 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:25,635 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:25,635 - util.py[DEBUG]: Read 971 bytes from /proc/self/status
2019-07-22 11:54:25,638 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2019-07-22 11:54:25,638 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:25,639 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2019-07-22 11:54:25,639 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2019-07-22 11:54:25,639 - util.py[DEBUG]: Reading from /sys/devices/vbd-768/block/xvda/dev (quiet=False)
2019-07-22 11:54:25,639 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-768/block/xvda/dev
2019-07-22 11:54:25,639 - util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,674 - util.py[DEBUG]: Running command ['growpart', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,735 - util.py[DEBUG]: resize_devices took 0.106 seconds
2019-07-22 11:54:25,735 - cc_growpart.py[INFO]: '/' resized: changed (/dev/xvda, 1) from 8588869120 to 32211189248
2019-07-22 11:54:25,736 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2019-07-22 11:54:25,736 - stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2019-07-22 11:54:25,736 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2019-07-22 11:54:25,736 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea588fef0>)
2019-07-22 11:54:25,736 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present
2019-07-22 11:54:25,736 - util.py[DEBUG]: Reading from /proc/1325/mountinfo (quiet=False)
2019-07-22 11:54:25,737 - util.py[DEBUG]: Read 2627 bytes from /proc/1325/mountinfo
2019-07-22 11:54:25,737 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2019-07-22 11:54:25,737 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,739 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,741 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,743 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2019-07-22 11:54:25,743 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2019-07-22 11:54:25,743 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2019-07-22 11:54:25,743 - util.py[DEBUG]: Read 972 bytes from /proc/self/status
2019-07-22 11:54:25,743 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
2019-07-22 11:54:25,743 - util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,782 - util.py[DEBUG]: Resizing took 0.038 seconds
2019-07-22 11:54:25,782 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2019-07-22 11:54:25,782 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2019-07-22 11:54:25,782 - stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2019-07-22 11:54:25,782 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2019-07-22 11:54:25,782 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_disk_setup - wb: [644] 25 bytes
2019-07-22 11:54:25,783 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_disk_setup'>)
2019-07-22 11:54:25,783 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2019-07-22 11:54:25,783 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2019-07-22 11:54:25,783 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2019-07-22 11:54:25,783 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_mounts - wb: [644] 25 bytes
2019-07-22 11:54:25,784 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_mounts'>)
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: mounts configuration is []
2019-07-22 11:54:25,784 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2019-07-22 11:54:25,784 - util.py[DEBUG]: Read 51 bytes from /etc/fstab
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2019-07-22 11:54:25,784 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2019-07-22 11:54:25,784 - cc_mounts.py[DEBUG]: changed default device swap => None
2019-07-22 11:54:25,785 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2019-07-22 11:54:25,785 - cc_mounts.py[DEBUG]: no need to setup swap
2019-07-22 11:54:25,785 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2019-07-22 11:54:25,785 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2019-07-22 11:54:25,785 - stages.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2019-07-22 11:54:25,785 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2019-07-22 11:54:25,785 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_set_hostname - wb: [644] 25 bytes
2019-07-22 11:54:25,785 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_set_hostname'>)
2019-07-22 11:54:25,785 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2019-07-22 11:54:25,786 - util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
2019-07-22 11:54:25,786 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2019-07-22 11:54:25,786 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2019-07-22 11:54:25,786 - stages.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2019-07-22 11:54:25,786 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2019-07-22 11:54:25,786 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea588f5f8>)
2019-07-22 11:54:25,786 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-0-194.eu-west-1.compute.internal (ip-10-0-0-194)
2019-07-22 11:54:25,786 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2019-07-22 11:54:25,786 - util.py[DEBUG]: Read 14 bytes from /etc/hostname
2019-07-22 11:54:25,786 - __init__.py[DEBUG]: Attempting to update hostname to ip-10-0-0-194 in 1 files
2019-07-22 11:54:25,786 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2019-07-22 11:54:25,786 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 14 bytes
2019-07-22 11:54:25,787 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2019-07-22 11:54:25,787 - stages.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2019-07-22 11:54:25,787 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2019-07-22 11:54:25,787 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f7ea5886710>)
2019-07-22 11:54:25,787 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2019-07-22 11:54:25,787 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2019-07-22 11:54:25,787 - stages.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2019-07-22 11:54:25,788 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2019-07-22 11:54:25,788 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ca_certs - wb: [644] 24 bytes
2019-07-22 11:54:25,788 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ca_certs'>)
2019-07-22 11:54:25,788 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca-certs' key in configuration
2019-07-22 11:54:25,788 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2019-07-22 11:54:25,788 - stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2019-07-22 11:54:25,788 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2019-07-22 11:54:25,788 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_rsyslog - wb: [644] 25 bytes
2019-07-22 11:54:25,789 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_rsyslog'>)
2019-07-22 11:54:25,789 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2019-07-22 11:54:25,789 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2019-07-22 11:54:25,789 - stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2019-07-22 11:54:25,789 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2019-07-22 11:54:25,789 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_users_groups - wb: [644] 25 bytes
2019-07-22 11:54:25,790 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_users_groups'>)
2019-07-22 11:54:25,790 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:25,790 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:25,790 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:25,790 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:25,791 - __init__.py[DEBUG]: Adding user ubuntu
2019-07-22 11:54:25,791 - util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2019-07-22 11:54:25,850 - util.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,862 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2019-07-22 11:54:25,863 - util.py[DEBUG]: Read 755 bytes from /etc/sudoers
2019-07-22 11:54:25,864 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 151 bytes
2019-07-22 11:54:25,864 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2019-07-22 11:54:25,864 - stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2019-07-22 11:54:25,865 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2019-07-22 11:54:25,865 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh - wb: [644] 25 bytes
2019-07-22 11:54:25,865 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh'>)
2019-07-22 11:54:25,866 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,929 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,965 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,968 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:25,973 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2019-07-22 11:54:25,973 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:25,973 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:25,974 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 448 bytes
2019-07-22 11:54:25,975 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2019-07-22 11:54:25,975 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2019-07-22 11:54:25,975 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:25,975 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:25,976 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 603 bytes
2019-07-22 11:54:25,976 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2019-07-22 11:54:25,976 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2019-07-22 11:54:25,976 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:25,977 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:25,977 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2019-07-22 11:54:25,977 - util.py[DEBUG]: cloud-init mode 'init' took 0.517 seconds (0.52)
2019-07-22 11:54:25,977 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2019-07-22 11:54:32,258 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:config' at Mon, 22 Jul 2019 11:54:32 +0000. Up 13.52 seconds.
2019-07-22 11:54:32,316 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:32,316 - stages.py[DEBUG]: Running module emit_upstart (<module 'cloudinit.config.cc_emit_upstart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_emit_upstart.py'>) with frequency always
2019-07-22 11:54:32,317 - handlers.py[DEBUG]: start: modules-config/config-emit_upstart: running config-emit_upstart with frequency always
2019-07-22 11:54:32,317 - helpers.py[DEBUG]: Running config-emit_upstart using lock (<cloudinit.helpers.DummyLock object at 0x7fb5298b8f98>)
2019-07-22 11:54:32,317 - cc_emit_upstart.py[DEBUG]: no /sbin/initctl located
2019-07-22 11:54:32,317 - cc_emit_upstart.py[DEBUG]: not upstart system, 'emit_upstart' disabled
2019-07-22 11:54:32,317 - handlers.py[DEBUG]: finish: modules-config/config-emit_upstart: SUCCESS: config-emit_upstart ran successfully
2019-07-22 11:54:32,317 - stages.py[DEBUG]: Running module snap (<module 'cloudinit.config.cc_snap' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap.py'>) with frequency once-per-instance
2019-07-22 11:54:32,317 - handlers.py[DEBUG]: start: modules-config/config-snap: running config-snap with frequency once-per-instance
2019-07-22 11:54:32,317 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snap - wb: [644] 24 bytes
2019-07-22 11:54:32,318 - helpers.py[DEBUG]: Running config-snap using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snap'>)
2019-07-22 11:54:32,318 - cc_snap.py[DEBUG]: Skipping module named snap, no 'snap' key in configuration
2019-07-22 11:54:32,318 - handlers.py[DEBUG]: finish: modules-config/config-snap: SUCCESS: config-snap ran successfully
2019-07-22 11:54:32,318 - stages.py[DEBUG]: Running module snap_config (<module 'cloudinit.config.cc_snap_config' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap_config.py'>) with frequency once-per-instance
2019-07-22 11:54:32,318 - handlers.py[DEBUG]: start: modules-config/config-snap_config: running config-snap_config with frequency once-per-instance
2019-07-22 11:54:32,318 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snap_config - wb: [644] 24 bytes
2019-07-22 11:54:32,319 - helpers.py[DEBUG]: Running config-snap_config using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snap_config'>)
2019-07-22 11:54:32,319 - cc_snap_config.py[DEBUG]: No snappy config provided, skipping
2019-07-22 11:54:32,319 - handlers.py[DEBUG]: finish: modules-config/config-snap_config: SUCCESS: config-snap_config ran successfully
2019-07-22 11:54:32,319 - stages.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2019-07-22 11:54:32,319 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2019-07-22 11:54:32,319 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh_import_id - wb: [644] 25 bytes
2019-07-22 11:54:32,320 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh_import_id'>)
2019-07-22 11:54:32,320 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2019-07-22 11:54:32,320 - stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2019-07-22 11:54:32,320 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2019-07-22 11:54:32,320 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_locale - wb: [644] 25 bytes
2019-07-22 11:54:32,321 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_locale'>)
2019-07-22 11:54:32,321 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:32,321 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:32,321 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2019-07-22 11:54:32,321 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2019-07-22 11:54:32,321 - util.py[DEBUG]: Read 35 bytes from /etc/default/locale
2019-07-22 11:54:32,321 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2019-07-22 11:54:32,321 - util.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:32,954 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2019-07-22 11:54:32,954 - util.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2019-07-22 11:54:33,002 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2019-07-22 11:54:33,002 - stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2019-07-22 11:54:33,002 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2019-07-22 11:54:33,002 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_set_passwords - wb: [644] 25 bytes
2019-07-22 11:54:33,003 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_set_passwords'>)
2019-07-22 11:54:33,003 - cc_set_passwords.py[DEBUG]: Leaving ssh config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2019-07-22 11:54:33,003 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2019-07-22 11:54:33,003 - stages.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2019-07-22 11:54:33,003 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2019-07-22 11:54:33,004 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_grub_dpkg - wb: [644] 25 bytes
2019-07-22 11:54:33,004 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_grub_dpkg'>)
2019-07-22 11:54:33,004 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/xvda','false'
2019-07-22 11:54:33,004 - util.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,145 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2019-07-22 11:54:33,145 - stages.py[DEBUG]: Running module apt-pipelining (<module 'cloudinit.config.cc_apt_pipelining' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_pipelining.py'>) with frequency once-per-instance
2019-07-22 11:54:33,146 - handlers.py[DEBUG]: start: modules-config/config-apt-pipelining: running config-apt-pipelining with frequency once-per-instance
2019-07-22 11:54:33,146 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_apt_pipelining - wb: [644] 24 bytes
2019-07-22 11:54:33,147 - helpers.py[DEBUG]: Running config-apt-pipelining using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_apt_pipelining'>)
2019-07-22 11:54:33,147 - util.py[DEBUG]: Writing to /etc/apt/apt.conf.d/90cloud-init-pipelining - wb: [644] 80 bytes
2019-07-22 11:54:33,147 - cc_apt_pipelining.py[DEBUG]: Wrote /etc/apt/apt.conf.d/90cloud-init-pipelining with apt pipeline depth setting 0
2019-07-22 11:54:33,147 - handlers.py[DEBUG]: finish: modules-config/config-apt-pipelining: SUCCESS: config-apt-pipelining ran successfully
2019-07-22 11:54:33,147 - stages.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2019-07-22 11:54:33,147 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2019-07-22 11:54:33,147 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_apt_configure - wb: [644] 25 bytes
2019-07-22 11:54:33,148 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_apt_configure'>)
2019-07-22 11:54:33,148 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2019-07-22 11:54:33,148 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:33,148 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:33,148 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:33,148 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:33,149 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2019-07-22 11:54:33,149 - util.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,192 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,194 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2019-07-22 11:54:33,195 - cc_apt_configure.py[DEBUG]: got security mirror: None
2019-07-22 11:54:33,195 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,227 - util.py[DEBUG]: Resolving URL: http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ took 0.031 seconds
2019-07-22 11:54:33,228 - __init__.py[DEBUG]: filtered distro mirror info: {'security': 'http://security.ubuntu.com/ubuntu', 'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/'}
2019-07-22 11:54:33,228 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'security': 'http://security.ubuntu.com/ubuntu', 'primary': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'PRIMARY': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'MIRROR': 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/', 'SECURITY': 'http://security.ubuntu.com/ubuntu'}
2019-07-22 11:54:33,228 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2019-07-22 11:54:33,228 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.tmpl (quiet=False)
2019-07-22 11:54:33,229 - util.py[DEBUG]: Read 2841 bytes from /etc/cloud/templates/sources.list.ubuntu.tmpl
2019-07-22 11:54:33,236 - util.py[DEBUG]: Writing to /etc/apt/sources.list - wb: [644] 3335 bytes
2019-07-22 11:54:33,236 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_i18n_Translation-en
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_multiverse_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_i18n_Translation-en
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-amd64_Packages
2019-07-22 11:54:33,239 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_i18n_Translation-en
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_InRelease
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_i18n_Translation-en
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_i18n_Translation-en to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_i18n_Translation-en
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_binary-amd64_Packages
2019-07-22 11:54:33,240 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages to /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages
2019-07-22 11:54:33,240 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2019-07-22 11:54:33,240 - stages.py[DEBUG]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) with frequency once-per-instance
2019-07-22 11:54:33,241 - handlers.py[DEBUG]: start: modules-config/config-ubuntu-advantage: running config-ubuntu-advantage with frequency once-per-instance
2019-07-22 11:54:33,241 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ubuntu_advantage - wb: [644] 25 bytes
2019-07-22 11:54:33,241 - helpers.py[DEBUG]: Running config-ubuntu-advantage using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ubuntu_advantage'>)
2019-07-22 11:54:33,241 - cc_ubuntu_advantage.py[DEBUG]: Skipping module named ubuntu-advantage, no 'ubuntu-advantage' key in configuration
2019-07-22 11:54:33,241 - handlers.py[DEBUG]: finish: modules-config/config-ubuntu-advantage: SUCCESS: config-ubuntu-advantage ran successfully
2019-07-22 11:54:33,241 - stages.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2019-07-22 11:54:33,241 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2019-07-22 11:54:33,242 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ntp - wb: [644] 25 bytes
2019-07-22 11:54:33,242 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ntp'>)
2019-07-22 11:54:33,242 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2019-07-22 11:54:33,242 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2019-07-22 11:54:33,242 - stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2019-07-22 11:54:33,242 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2019-07-22 11:54:33,242 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_timezone - wb: [644] 25 bytes
2019-07-22 11:54:33,243 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_timezone'>)
2019-07-22 11:54:33,243 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2019-07-22 11:54:33,243 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2019-07-22 11:54:33,243 - stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2019-07-22 11:54:33,243 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2019-07-22 11:54:33,243 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb52912b080>)
2019-07-22 11:54:33,243 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2019-07-22 11:54:33,243 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2019-07-22 11:54:33,243 - stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2019-07-22 11:54:33,243 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2019-07-22 11:54:33,244 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_runcmd - wb: [644] 25 bytes
2019-07-22 11:54:33,244 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_runcmd'>)
2019-07-22 11:54:33,244 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2019-07-22 11:54:33,244 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2019-07-22 11:54:33,244 - stages.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2019-07-22 11:54:33,244 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2019-07-22 11:54:33,244 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_byobu - wb: [644] 24 bytes
2019-07-22 11:54:33,245 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_byobu'>)
2019-07-22 11:54:33,245 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2019-07-22 11:54:33,245 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2019-07-22 11:54:33,245 - main.py[DEBUG]: Ran 15 modules with 0 failures
2019-07-22 11:54:33,246 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:33,246 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:33,246 - util.py[DEBUG]: cloud-init mode 'modules' took 1.033 seconds (1.03)
2019-07-22 11:54:33,246 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2019-07-22 11:54:33,539 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:final' at Mon, 22 Jul 2019 11:54:33 +0000. Up 14.80 seconds.
2019-07-22 11:54:33,576 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2019-07-22 11:54:33,576 - stages.py[DEBUG]: Running module snappy (<module 'cloudinit.config.cc_snappy' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snappy.py'>) with frequency once-per-instance
2019-07-22 11:54:33,577 - handlers.py[DEBUG]: start: modules-final/config-snappy: running config-snappy with frequency once-per-instance
2019-07-22 11:54:33,577 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snappy - wb: [644] 25 bytes
2019-07-22 11:54:33,577 - helpers.py[DEBUG]: Running config-snappy using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_snappy'>)
2019-07-22 11:54:33,577 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2019-07-22 11:54:33,577 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2019-07-22 11:54:33,578 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2019-07-22 11:54:33,578 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2019-07-22 11:54:33,578 - cc_snappy.py[DEBUG]: snappy: 'auto' mode, and system not snappy
2019-07-22 11:54:33,578 - handlers.py[DEBUG]: finish: modules-final/config-snappy: SUCCESS: config-snappy ran successfully
2019-07-22 11:54:33,579 - stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance
2019-07-22 11:54:33,579 - handlers.py[DEBUG]: start: modules-final/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
2019-07-22 11:54:33,579 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_package_update_upgrade_install - wb: [644] 25 bytes
2019-07-22 11:54:33,579 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_package_update_upgrade_install'>)
2019-07-22 11:54:33,579 - handlers.py[DEBUG]: finish: modules-final/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
2019-07-22 11:54:33,579 - stages.py[DEBUG]: Running module fan (<module 'cloudinit.config.cc_fan' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_fan.py'>) with frequency once-per-instance
2019-07-22 11:54:33,580 - handlers.py[DEBUG]: start: modules-final/config-fan: running config-fan with frequency once-per-instance
2019-07-22 11:54:33,580 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_fan - wb: [644] 24 bytes
2019-07-22 11:54:33,580 - helpers.py[DEBUG]: Running config-fan using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_fan'>)
2019-07-22 11:54:33,580 - cc_fan.py[DEBUG]: fan: no 'fan' config entry. disabling
2019-07-22 11:54:33,580 - handlers.py[DEBUG]: finish: modules-final/config-fan: SUCCESS: config-fan ran successfully
2019-07-22 11:54:33,580 - stages.py[DEBUG]: Running module landscape (<module 'cloudinit.config.cc_landscape' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_landscape.py'>) with frequency once-per-instance
2019-07-22 11:54:33,580 - handlers.py[DEBUG]: start: modules-final/config-landscape: running config-landscape with frequency once-per-instance
2019-07-22 11:54:33,581 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_landscape - wb: [644] 25 bytes
2019-07-22 11:54:33,581 - helpers.py[DEBUG]: Running config-landscape using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_landscape'>)
2019-07-22 11:54:33,581 - handlers.py[DEBUG]: finish: modules-final/config-landscape: SUCCESS: config-landscape ran successfully
2019-07-22 11:54:33,581 - stages.py[DEBUG]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) with frequency once-per-instance
2019-07-22 11:54:33,581 - handlers.py[DEBUG]: start: modules-final/config-lxd: running config-lxd with frequency once-per-instance
2019-07-22 11:54:33,581 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_lxd - wb: [644] 25 bytes
2019-07-22 11:54:33,582 - helpers.py[DEBUG]: Running config-lxd using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_lxd'>)
2019-07-22 11:54:33,582 - cc_lxd.py[DEBUG]: Skipping module named lxd, not present or disabled by cfg
2019-07-22 11:54:33,582 - handlers.py[DEBUG]: finish: modules-final/config-lxd: SUCCESS: config-lxd ran successfully
2019-07-22 11:54:33,582 - stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_puppet.py'>) with frequency once-per-instance
2019-07-22 11:54:33,582 - handlers.py[DEBUG]: start: modules-final/config-puppet: running config-puppet with frequency once-per-instance
2019-07-22 11:54:33,582 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_puppet - wb: [644] 25 bytes
2019-07-22 11:54:33,583 - helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_puppet'>)
2019-07-22 11:54:33,583 - cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
2019-07-22 11:54:33,583 - handlers.py[DEBUG]: finish: modules-final/config-puppet: SUCCESS: config-puppet ran successfully
2019-07-22 11:54:33,583 - stages.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py'>) with frequency once-per-instance
2019-07-22 11:54:33,583 - handlers.py[DEBUG]: start: modules-final/config-chef: running config-chef with frequency once-per-instance
2019-07-22 11:54:33,583 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_chef - wb: [644] 25 bytes
2019-07-22 11:54:33,583 - helpers.py[DEBUG]: Running config-chef using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_chef'>)
2019-07-22 11:54:33,583 - cc_chef.py[DEBUG]: Skipping module named chef, no 'chef' key in configuration
2019-07-22 11:54:33,584 - handlers.py[DEBUG]: finish: modules-final/config-chef: SUCCESS: config-chef ran successfully
2019-07-22 11:54:33,584 - stages.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mcollective.py'>) with frequency once-per-instance
2019-07-22 11:54:33,584 - handlers.py[DEBUG]: start: modules-final/config-mcollective: running config-mcollective with frequency once-per-instance
2019-07-22 11:54:33,584 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_mcollective - wb: [644] 25 bytes
2019-07-22 11:54:33,584 - helpers.py[DEBUG]: Running config-mcollective using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_mcollective'>)
2019-07-22 11:54:33,584 - cc_mcollective.py[DEBUG]: Skipping module named mcollective, no 'mcollective' key in configuration
2019-07-22 11:54:33,584 - handlers.py[DEBUG]: finish: modules-final/config-mcollective: SUCCESS: config-mcollective ran successfully
2019-07-22 11:54:33,584 - stages.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_salt_minion.py'>) with frequency once-per-instance
2019-07-22 11:54:33,585 - handlers.py[DEBUG]: start: modules-final/config-salt-minion: running config-salt-minion with frequency once-per-instance
2019-07-22 11:54:33,585 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_salt_minion - wb: [644] 25 bytes
2019-07-22 11:54:33,585 - helpers.py[DEBUG]: Running config-salt-minion using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_salt_minion'>)
2019-07-22 11:54:33,585 - cc_salt_minion.py[DEBUG]: Skipping module named salt-minion, no 'salt_minion' key in configuration
2019-07-22 11:54:33,585 - handlers.py[DEBUG]: finish: modules-final/config-salt-minion: SUCCESS: config-salt-minion ran successfully
2019-07-22 11:54:33,585 - stages.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2019-07-22 11:54:33,585 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2019-07-22 11:54:33,586 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_rightscale_userdata - wb: [644] 25 bytes
2019-07-22 11:54:33,586 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_rightscale_userdata'>)
2019-07-22 11:54:33,586 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2019-07-22 11:54:33,586 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2019-07-22 11:54:33,586 - stages.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2019-07-22 11:54:33,586 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2019-07-22 11:54:33,586 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_vendor - wb: [644] 25 bytes
2019-07-22 11:54:33,587 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_vendor'>)
2019-07-22 11:54:33,587 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2019-07-22 11:54:33,587 - stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2019-07-22 11:54:33,587 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2019-07-22 11:54:33,587 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2019-07-22 11:54:33,588 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2019-07-22 11:54:33,588 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2019-07-22 11:54:33,588 - stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2019-07-22 11:54:33,588 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2019-07-22 11:54:33,588 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f7fd79c5908>)
2019-07-22 11:54:33,588 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2019-07-22 11:54:33,588 - stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2019-07-22 11:54:33,588 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2019-07-22 11:54:33,588 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_per_instance - wb: [644] 24 bytes
2019-07-22 11:54:33,589 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_per_instance'>)
2019-07-22 11:54:33,589 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2019-07-22 11:54:33,589 - stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2019-07-22 11:54:33,589 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2019-07-22 11:54:33,589 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_user - wb: [644] 25 bytes
2019-07-22 11:54:33,590 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_scripts_user'>)
2019-07-22 11:54:33,590 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2019-07-22 11:54:33,590 - stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2019-07-22 11:54:33,590 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2019-07-22 11:54:33,590 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2019-07-22 11:54:33,590 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_ssh_authkey_fingerprints'>)
2019-07-22 11:54:33,591 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2019-07-22 11:54:33,591 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2019-07-22 11:54:33,591 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2019-07-22 11:54:33,591 - util.py[DEBUG]: Read 448 bytes from /home/ubuntu/.ssh/authorized_keys
2019-07-22 11:54:33,634 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2019-07-22 11:54:33,634 - stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2019-07-22 11:54:33,634 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2019-07-22 11:54:33,635 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_keys_to_console - wb: [644] 25 bytes
2019-07-22 11:54:33,635 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_keys_to_console'>)
2019-07-22 11:54:33,635 - util.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2019-07-22 11:54:33,650 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2019-07-22 11:54:33,651 - stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2019-07-22 11:54:33,651 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2019-07-22 11:54:33,651 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_phone_home - wb: [644] 25 bytes
2019-07-22 11:54:33,651 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_phone_home'>)
2019-07-22 11:54:33,652 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2019-07-22 11:54:33,652 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2019-07-22 11:54:33,652 - stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2019-07-22 11:54:33,652 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2019-07-22 11:54:33,652 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f7fd7233198>)
2019-07-22 11:54:33,652 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:33,652 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:33,655 - util.py[DEBUG]: Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 finished at Mon, 22 Jul 2019 11:54:33 +0000. Datasource DataSourceEc2Local.  Up 14.96 seconds
2019-07-22 11:54:33,655 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 79 bytes
2019-07-22 11:54:33,655 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2019-07-22 11:54:33,656 - stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2019-07-22 11:54:33,656 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2019-07-22 11:54:33,656 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_power_state_change - wb: [644] 25 bytes
2019-07-22 11:54:33,656 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0801077bcefacb3ae/sem/config_power_state_change'>)
2019-07-22 11:54:33,656 - cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
2019-07-22 11:54:33,656 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2019-07-22 11:54:33,656 - main.py[DEBUG]: Ran 20 modules with 0 failures
2019-07-22 11:54:33,657 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2019-07-22 11:54:33,657 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2019-07-22 11:54:33,657 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2019-07-22 11:54:33,657 - util.py[DEBUG]: cloud-init mode 'modules' took 0.163 seconds (0.16)
2019-07-22 11:54:33,657 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
